let gameState = {
    players: [],
    currentИгрок: 0,
    civilianWord: '',
    undercoverWord: '',
    eliminatedИгрокs: new Set(),
    selectedКатегории: ['Food & Drink', 'Animals', 'Objects', 'Jobs & Roles', 'Entertainment', 'Nature & Weather', 'Funny', 'Movies', 'Internet Slang'],
    premiumКатегории: ['Sports & Fitness', 'Technology & Digital', 'Travel & Places', 'Relationships', 'Brands & Companies', 'Historical Figures'],
    wordsByCategory: {
        'Food & Drink': [
            ['Pizza', 'Burger'],
            ['Coffee', 'Tea'],
            ['Soda', 'Juice'],
            ['Apple', 'Orange'],
            ['Candy Bar', 'Granola Bar'],
            ['Hot Sauce', 'Ketchup'],
            ['Muffin', 'Cupcake'],
            ['Bread', 'Toast'],
            ['Milk', 'Cream'],
            ['Ice Cream', 'Cake'],
            ['Bacon', 'Ham'],
            ['Soup', 'Salad'],
            ['Cookie', 'Brownie'],
            ['Espresso', 'Latte'],
            ['Sandwich', 'Wrap'],
            ['Pasta', 'Rice'],
            ['Cheese', 'Butter'],
            ['Ramen', 'Pho'],
            ['Water', 'Soda'],
            ['Chicken', 'Fish'],
            ['Banana', 'Grape'],
            ['Yogurt', 'Pudding'],
            ['Donut', 'Bagel'],
            ['Honey', 'Sugar'],
            ['Steak', 'Pork'],
            ['Wine', 'Beer'],
            ['Cereal', 'Oatmeal'],
            ['Noodles', 'Spaghetti'],
            ['Egg', 'Omelet'],
            ['Pickle', 'Olive'],
            ['Pancake', 'Waffle'],
            ['Waffle', 'Crepe'],
            ['Hotdog', 'Sausage'],
            ['Taco', 'Burrito'],
            ['Chips', 'Popcorn'],
            ['Strawberry', 'Blueberry'],
            ['Watermelon', 'Яlon'],
            ['Carrot', 'Broccoli'],
            ['Tomato', 'Cucumber'],
            ['Spinach', 'Lettuce'],
            ['Chocolate', 'Vanilla'],
            ['Soy Sauce', 'Vinegar'],
            ['Olive Oil', 'Vegetable Oil'],
            ['Garlic', 'Onion'],
            ['Pepper', 'Salt'],
            ['Mustard', 'Mayo'],
            ['Peanut Butter', 'Almond Butter'],
            ['Jam', 'Jelly'],
            ['Spaghetti Sauce', 'Marinara'],
            ['BBQ Sauce', 'Worcestershire'],
            ['Lemonade', 'Iced Tea'],
            ['Ketchup', 'Mustard'],
            ['Jam', 'Marmalade'],
            ['Waffle', 'Pancake'],
            ['Sausage', 'Bacon'],
            ['Ham', 'Turkey'],
            ['Lettuce', 'Spinach'],
            ['Celery', 'Radish'],
            ['Potato', 'Corn'],
            ['Peas', 'Beans'],
            ['Asparagus', 'Brussels Sprout'],
            ['Cabbage', 'Kale'],
            ['Beet', 'Turnip'],
            ['Mushroom', 'Truffle'],
            ['Shrimp', 'Crab'],
            ['Tuna', 'Salmon'],
            ['Beef', 'Veal'],
            ['Lamb', 'Venison'],
            ['Duck', 'Pheasant'],
            ['Lime', 'Lemon'],
            ['Cherry', 'Plum'],
            ['Peach', 'Apricot'],
            ['Pineapple', 'Mango'],
            ['Avocado', 'Coconut'],
            ['Walnut', 'Almond'],
            ['Peanut', 'Cashew'],
            ['Raisin', 'Cranberry'],
            ['Oatmeal', 'Granola'],
            ['Yogurt Drink', 'Smoothie'],
            ['Fresh Juice', 'Milkshake'],
            ['Vanilla Ice Cream', 'Chocolate Ice Cream'],
            ['Whipped Cream', 'Frosting'],
            ['Dressing', 'Sauce'],
            ['Garlic Bread', 'Herb Bread'],
            ['Rice Bowl', 'Pasta Plate'],
            ['Яat Pie', 'Chicken Pie'],
            ['Fish and Chips', 'Fried Chicken'],
            ['Sushi Roll', 'Spring Roll'],
            ['Pizza Slice', 'Pizza Pie'],
            ['Hot Dog', 'Corn Dog'],
            ['French Fries', 'Fried Potatoes'],
            ['Chicken Nuggets', 'Chicken Strips'],
            ['Mac and Cheese', 'Pasta with Cheese'],
            ['Peanut Butter Jelly', 'PB&J'],
            ['Grilled Cheese', 'Cheese Sandwich'],
            ['Buttered Popcorn', 'Popcorn'],
            ['Candy Cane', 'Lollipop'],
            ['Gummy Bears', 'Gummy Worms'],
            ['Jelly Beans', 'M&Ms'],
            ['Root Beer', 'Cola'],
            ['Iced Coffee', 'Cold Coffee'],
            ['Fruit Juice', 'Smoothie'],
            ['Candy', 'Sweet'],
            ['Snack', 'Treat'],
            ['Dessert', 'Cake'],
            ['Appetizer', 'Starter'],
            ['Main Course', 'Entree'],
            ['Fries', 'Chips'],
            ['Ice Pop', 'Popsicle'],
            ['Dumpling', 'Wonton']
        ],
        'Animals': [
            ['Cat', 'Dog'],
            ['Lion', 'Tiger'],
            ['Puppy', 'Bunny'],
            ['Bird', 'Fish'],
            ['Cow', 'Horse'],
            ['Goldfish', 'Guppy'],
            ['Peacock', 'Turkey'],
            ['Otter', 'Beaver'],
            ['Mouse', 'Rat'],
            ['Duck', 'Goose'],
            ['Bear', 'Wolf'],
            ['Crab', 'Lobster'],
            ['Snake', 'Lizard'],
            ['Goat', 'Sheep'],
            ['Eagle', 'Hawk'],
            ['Frog', 'Toad'],
            ['Monkey', 'Ape'],
            ['Deer', 'Elk'],
            ['Butterfly', 'Moth'],
            ['Bee', 'Wasp'],
            ['Pig', 'Boar'],
            ['Chicken', 'Rooster'],
            ['Elephant', 'Rhino'],
            ['Zebra', 'Donkey'],
            ['Whale', 'Dolphin'],
            ['Shark', 'Ray'],
            ['Turtle', 'Tortoise'],
            ['Owl', 'Crow'],
            ['Fox', 'Raccoon'],
            ['Squirrel', 'Chipmunk'],
            ['Kitten', 'Puppy'],
            ['Parrot', 'Canary'],
            ['Penguin', 'Puffin'],
            ['Hamster', 'Gerbil'],
            ['Ladybug', 'Dragonfly'],
            ['Ant', 'Spider'],
            ['Snail', 'Slug'],
            ['Penguin', 'Puffin'],
            ['Camel', 'Llama'],
            ['Cheetah', 'Leopard'],
            ['Seal', 'Sea Lion'],
            ['Alligator', 'Crocodile'],
            ['Peacock', 'Pheasant'],
            ['Eel', 'Catfish'],
            ['Bat', 'Moth'],
            ['Mink', 'Weasel'],
            ['Ostrich', 'Flamingo'],
            ['Koala', 'Panda'],
            ['Chimpanzee', 'Gorilla'],
            ['Giraffe', 'Wildebeest'],
            ['Lemur', 'Loris'],
            ['Hedgehog', 'Porcupine'],
            ['Badger', 'Otter'],
            ['Sloth', 'Koala'],
            ['Armadillo', 'Pangolin'],
            ['Anteater', 'Aardvark'],
            ['Hyena', 'Jackal'],
            ['Lynx', 'Bobcat'],
            ['Яerkat', 'Mongoose'],
            ['Chinchilla', 'Guinea Pig'],
            ['Rabbit', 'Hare'],
            ['Porcupine', 'Hedgehog'],
            ['Wombat', 'Tasmanian Devil'],
            ['Emu', 'Rhea'],
            ['Capybara', 'Nutria'],
            ['Bison', 'Buffalo'],
            ['Moose', 'Reindeer'],
            ['Okapi', 'Tapir'],
            ['Quetzal', 'Macaw'],
            ['Sparrow', 'Finch'],
            ['Walrus', 'Seal'],
            ['Orca', 'Whale'],
            ['Antelope', 'Gazelle'],
            ['Newt', 'Salamander'],
            ['Egret', 'Heron'],
            ['Jackal', 'Hyena'],
            ['Emu', 'Ostrich'],
            ['Tortoise', 'Turtle'],
            ['Viper', 'Python'],
            ['Ibis', 'Stork'],
            ['Tern', 'Gull'],
            ['Tapir', 'Aardvark'],
            ['Lemming', 'Vole'],
            ['Newt', 'Toad'],
            ['Macaw', 'Parrot'],
            ['Cheetah', 'Puma'],
            ['Porcupine', 'Hedgehog'],
            ['Llama', 'Alpaca'],
            ['Giraffe', 'Ostrich'],
            ['Kangaroo', 'Koala'],
            ['Panda', 'Penguin'],
            ['Sloth', 'Armadillo'],
            ['Platypus', 'Echidna'],
            ['Octopus', 'Squid'],
            ['Jellyfish', 'Starfish'],
            ['Lobster', 'Shrimp'],
            ['Clam', 'Oyster'],
            ['Snail', 'Slug'],
            ['Worm', 'Caterpillar'],
            ['Bee', 'Butterfly'],
            ['Ant', 'Termite'],
            ['Grasshopper', 'Cricket'],
            ['Lizard', 'Iguana'],
            ['Seahorse', 'Seadragon'],
            ['Mole', 'Badger'],
            ['Seal', 'Sea Lion'],
            ['Manatee', 'Dugong'],
            ['Penguin', 'Puffin'],
            ['Chipmunk', 'Squirrel'],
            ['Albatross', 'Pelican']
        ],
        'Objects': [
            ['Phone', 'Tablet'],
            ['Chair', 'Sofa'],
            ['Book', 'Magazine'],
            ['Pen', 'Pencil'],
            ['Car', 'Bus'],
            ['Watch', 'Clock'],
            ['Bag', 'Backpack'],
            ['Cup', 'Glass'],
            ['Key', 'Lock'],
            ['Shoes', 'Boots'],
            ['Hat', 'Cap'],
            ['Camera', 'Phone'],
            ['Lamp', 'Candle'],
            ['Mirror', 'Window'],
            ['Plate', 'Bowl'],
            ['Spoon', 'Fork'],
            ['Towel', 'Cloth'],
            ['Pillow', 'Blanket'],
            ['Remote', 'Controller'],
            ['Wallet', 'Purse'],
            ['Bicycle', 'Motorcycle'],
            ['Computer', 'Laptop'],
            ['TV', 'Monitor'],
            ['Fridge', 'Freezer'],
            ['Microwave', 'Oven'],
            ['Brush', 'Comb'],
            ['Knife', 'Scissors'],
            ['Umbrella', 'Raincoat'],
            ['Bottle', 'Can'],
            ['Box', 'Bag'],
            ['Bed', 'Mattress'],
            ['Table', 'Desk'],
            ['Door', 'Window'],
            ['Wall', 'Пол'],
            ['Carpet', 'Rug'],
            ['Poster', 'Picture Frame'],
            ['Desk', 'Office Chair'],
            ['Pen', 'Marker'],
            ['Eraser', 'Whiteboard'],
            ['Notebook', 'Notepad'],
            ['Sticky Notes', 'Яmo'],
            ['Ruler', 'Protractor'],
            ['Scissors', 'Tape'],
            ['Glue', 'Stapler'],
            ['Paper Clip', 'Pushpin'],
            ['Rubber Band', 'Clothespin'],
            ['Trash Can', 'Waste Basket'],
            ['Coat Hanger', 'Closet Rod'],
            ['Hangers', 'Hooks'],
            ['Drawer', 'Cabinet'],
            ['Sink', 'Basin'],
            ['Bathtub', 'Shower'],
            ['Toilet', 'Bidet'],
            ['Mirror', 'Frame'],
            ['Picture', 'Artwork'],
            ['Rug', 'Mat'],
            ['Shelf', 'Ledge'],
            ['Bookcase', 'Cabinet'],
            ['Dresser', 'Wardrobe'],
            ['Nightstand', 'Side Table'],
            ['Coat Rack', 'Umbrella Stand'],
            ['Picture Frame', 'Mirror'],
            ['Candle', 'Lantern'],
            ['Vase', 'Pot'],
            ['Painting', 'Sculpture'],
            ['Ornament', 'Decoration'],
            ['Plants', 'Flowers'],
            ['Clock', 'Sundial'],
            ['Rug', 'Tapestry'],
            ['Sofa', 'Armchair'],
            ['Desk', 'Table'],
            ['Stool', 'Bench'],
            ['Closet', 'Wardrobe'],
            ['Shelf', 'Cabinet'],
            ['Basket', 'Container'],
            ['Curtain', 'Blinds'],
            ['Cushion', 'Pillow'],
            ['Mat', 'Rug'],
            ['Pot', 'Pan'],
            ['Bowl', 'Plate'],
            ['Cup', 'Mug'],
            ['Fork', 'Spoon'],
            ['Knife', 'Blade'],
            ['Bag', 'Purse'],
            ['Case', 'Box'],
            ['Trunk', 'Chest'],
            ['Rack', 'Hanger'],
            ['Lamp', 'Light'],
            ['Couch', 'Sofa'],
            ['Bench', 'Stool'],
            ['Locker', 'Cabinet'],
            ['Bin', 'Container'],
            ['Jar', 'Can'],
            ['Plate', 'Dish'],
            ['Bowl', 'Cup'],
            ['Glass', 'Mug'],
            ['Utensil', 'Silverware'],
            ['Napkin', 'Tissue'],
            ['Blanket', 'Sheet'],
            ['Mattress', 'Bed'],
            ['Pillow', 'Cushion'],
            ['Curtain', 'Shade'],
            ['Drawer', 'Shelf'],
            ['Door', 'Gate'],
            ['Window', 'Porthole'],
            ['Wall', 'Partition'],
            ['Пол', 'Ground'],
            ['Backpack', 'Rucksack'],
            ['Mirror', 'Reflector'],
            ['Ruler', 'Яasuring Tape']
        ],
        'Jobs & Roles': [
            ['Teacher', 'Student'],
            ['Доктор', 'Nurse'],
            ['Chef', 'Waiter'],
            ['Police', 'Guard'],
            ['Driver', 'Pilot'],
            ['Singer', 'Dancer'],
            ['Writer', 'Editor'],
            ['Farmer', 'Gardener'],
            ['Artist', 'Designer'],
            ['Judge', 'Lawyer'],
            ['Banker', 'Cashier'],
            ['Actor', 'Director'],
            ['Яchanic', 'Engineer'],
            ['Manager', 'Boss'],
            ['Clerk', 'Secretary'],
            ['Soldier', 'Captain'],
            ['Dentist', 'Therapist'],
            ['Barber', 'Stylist'],
            ['Mailman', 'Delivery'],
            ['Cleaner', 'Janitor'],
            ['Librarian', 'Bookkeeper'],
            ['Photographer', 'Model'],
            ['Salesman', 'Customer'],
            ['Builder', 'Architect'],
            ['Scientist', 'Researcher'],
            ['Musician', 'Composer'],
            ['Journalist', 'Reporter'],
            ['Accountant', 'Auditor'],
            ['Translator', 'Interpreter'],
            ['Coach', 'Trainer'],
            ['Electrician', 'Plumber'],
            ['Carpenter', 'Painter'],
            ['Surgeon', 'Pharmacist'],
            ['Veterinarian', 'Groomer'],
            ['Florist', 'Baker'],
            ['Receptionist', 'Assistant'],
            ['Consultant', 'Advisor'],
            ['Manager', 'Supervisor'],
            ['Administrator', 'Director'],
            ['Technician', 'Specialist'],
            ['Analyst', 'Developer'],
            ['Officer', 'Agent'],
            ['Inspector', 'Investigator'],
            ['Instructor', 'Яntor'],
            ['Consultant', 'Expert'],
            ['Specialist', 'Professional'],
            ['Associate', 'Colleague'],
            ['Supervisor', 'Overseer'],
            ['Coordinator', 'Organizer'],
            ['Representative', 'Ambassador'],
            ['Cashier', 'Teller'],
            ['Pharmacist', 'Apothecary'],
            ['Optometrist', 'Ophthalmologist'],
            ['Electrician', 'Technician'],
            ['Plumber', 'Pipefitter'],
            ['Carpenter', 'Mason'],
            ['Painter', 'Decorator'],
            ['Electrician', 'Welder'],
            ['Baker', 'Pastry Chef'],
            ['Butcher', 'Fishmonger'],
            ['Grocer', 'Vendor'],
            ['Shopkeeper', 'Яrchant'],
            ['Blacksmith', 'Craftsman'],
            ['Artist', 'Sculptor'],
            ['Dancer', 'Choreographer'],
            ['Actor', 'Stunt Double'],
            ['Producer', 'Director'],
            ['Cameraman', 'Cinematographer'],
            ['Sound Engineer', 'Audio Tech'],
            ['Technician', 'Яchanic'],
            ['Administrator', 'Manager'],
            ['Coordinator', 'Organizer'],
            ['Consultant', 'Advisor'],
            ['Assistant', 'Deputy'],
            ['Supervisor', 'Inspector'],
            ['Officer', 'Agent'],
            ['Specialist', 'Expert'],
            ['Analyst', 'Researcher'],
            ['Developer', 'Programmer'],
            ['Designer', 'Illustrator'],
            ['Conductor', 'Performer'],
            ['Guide', 'Scout'],
            ['Caretaker', 'Keeper'],
            ['Operator', 'Technician'],
            ['Handler', 'Keeper'],
            ['Яntor', 'Coach'],
            ['Vendor', 'Яrchant'],
            ['Trader', 'Seller'],
            ['Referee', 'Umpire'],
            ['Lifeguard', 'Rescue Worker'],
            ['Receptionist', 'Secretary'],
            ['Accountant', 'Bookkeeper'],
            ['Scientist', 'Lab Tech'],
            ['Electrician', 'Lineman'],
            ['Plumber', 'Pipe Fitter'],
            ['Carpenter', 'Contractor'],
            ['Mason', 'Bricklayer'],
            ['Painter', 'Plasterer'],
            ['Gardener', 'Landscaper'],
            ['Florist', 'Horticulturist'],
            ['Chef', 'Cook'],
            ['Waiter', 'Server'],
            ['Bartender', 'Barista'],
            ['Receptionist', 'Front Desk'],
            ['Concierge', 'Bellhop'],
            ['Doorman', 'Security'],
            ['Janitor', 'Custodian'],
            ['Firefighter', 'Paramedic'],
            ['Hairdresser', 'Barber'],
            ['Cartoonist', 'Animator']
        ],
        'Entertainment': [
            ['Movie', 'TV Show'],
            ['Music', 'Song'],
            ['Game', 'Sport'],
            ['Party', 'Dance'],
            ['Book', 'Story'],
            ['Theater', 'Cinema'],
            ['Concert', 'Show'],
            ['Comedy', 'Drama'],
            ['Magic', 'Trick'],
            ['Cartoon', 'Anime'],
            ['Festival', 'Carnival'],
            ['Quiz', 'Contest'],
            ['Hobby', 'Activity'],
            ['Joke', 'Prank'],
            ['Performance', 'Act'],
            ['Radio', 'Podcast'],
            ['Karaoke', 'Singing'],
            ['Chess', 'Checkers'],
            ['Puzzle', 'Riddle'],
            ['Racing', 'Running'],
            ['Swimming', 'Diving'],
            ['Bowling', 'Golf'],
            ['Tennis', 'Badminton'],
            ['Basketball', 'Football'],
            ['Baseball', 'Soccer'],
            ['Painting', 'Drawing'],
            ['Cooking', 'Baking'],
            ['Reading', 'Writing'],
            ['Shopping', 'Browsing'],
            ['Traveling', 'Hiking'],
            ['Watching TV', 'Scrolling Phone'],
            ['Napping', 'Sleeping'],
            ['Coffee Break', 'Tea Time'],
            ['Jogging', 'Walking'],
            ['Cycling', 'Skateboarding'],
            ['Sketching', 'Doodling'],
            ['Singing', 'Humming'],
            ['Dancing', 'Swaying'],
            ['Listening', 'Watching'],
            ['Playing Instruments', 'Making Music'],
            ['Chatting', 'Gossiping'],
            ['Laughing', 'Smiling'],
            ['Playing Cards', 'Board Game'],
            ['Texting', 'Яssaging'],
            ['Calling', 'Video Chat'],
            ['Surfing', 'Sunbathing'],
            ['Picnicking', 'Grilling'],
            ['Gardening', 'Planting'],
            ['Exercising', 'Stretching'],
            ['Яditating', 'Relaxing'],
            ['Puzzles', 'Crossword'],
            ['Crafting', 'DIY'],
            ['Knitting', 'Sewing'],
            ['Scrapbooking', 'Journaling'],
            ['Photography', 'Videography'],
            ['Blogging', 'Vlogging'],
            ['Streaming', 'Broadcasting'],
            ['Practicing', 'Rehearsing'],
            ['Performing', 'Acting'],
            ['Comedy Show', 'Drama'],
            ['Concert', 'Festival'],
            ['Parade', 'Celebration'],
            ['Fireworks', 'Light Show'],
            ['Camping', 'Hiking'],
            ['Fishing', 'Hunting'],
            ['Archery', 'Darts'],
            ['Roller Skating', 'Ice Skating'],
            ['Skateboarding', 'Snowboarding'],
            ['Scuba Diving', 'Snorkeling'],
            ['Surfing', 'Skateboarding'],
            ['Running', 'Jogging'],
            ['Cycling', 'Biking'],
            ['Singing', 'Dancing'],
            ['Drawing', 'Painting'],
            ['Reading', 'Writing'],
            ['Cooking', 'Baking'],
            ['Photography', 'Videography'],
            ['Listening', 'Hearing'],
            ['Watching', 'Viewing'],
            ['Playing', 'Practicing'],
            ['Hobbies', 'Activities'],
            ['Chatting', 'Texting'],
            ['Hiking', 'Trekking'],
            ['Camping', 'Glamping'],
            ['Fishing', 'Hunting'],
            ['Golf', 'Bowling'],
            ['Tennis', 'Badminton'],
            ['Archery', 'Target Practice'],
            ['Karaoke', 'Singing'],
            ['Picnic', 'Barbecue'],
            ['Board Game', 'Card Game'],
            ['Video Game', 'Computer Game'],
            ['Party', 'Celebration'],
            ['Concert', 'Musical'],
            ['Comedy Show', 'Stand-up'],
            ['Play', 'Theater'],
            ['Movie Night', 'Film Time'],
            ['Basketball', 'Soccer'],
            ['Baseball', 'Softball'],
            ['Hockey', 'Lacrosse'],
            ['Rugby', 'American Football'],
            ['Volleyball', 'Badminton'],
            ['Checkers', 'Dominoes'],
            ['Billiards', 'Pool'],
            ['Darts', 'Cornhole'],
            ['Frisbee', 'Boomerang'],
            ['Kite', 'Balloon'],
            ['Singing', 'Karaoke'],
            ['Dancing', 'Ballet'],
            ['Juggling', 'Magic']
        ],
        'Nature & Weather': [
            ['Sun', 'Moon'],
            ['Rain', 'Snow'],
            ['Tree', 'Flower'],
            ['Mountain', 'Hill'],
            ['Ocean', 'Lake'],
            ['Wind', 'Breeze'],
            ['Cloud', 'Sky'],
            ['River', 'Stream'],
            ['Beach', 'Desert'],
            ['Forest', 'Garden'],
            ['Rock', 'Stone'],
            ['Fire', 'Ice'],
            ['Star', 'Planet'],
            ['Valley', 'Canyon'],
            ['Island', 'Coast'],
            ['Thunder', 'Lightning'],
            ['Fog', 'Mist'],
            ['Sunset', 'Sunrise'],
            ['Spring', 'Summer'],
            ['Winter', 'Autumn'],
            ['Grass', 'Moss'],
            ['Leaf', 'Branch'],
            ['Pond', 'Pool'],
            ['Field', 'Яadow'],
            ['Cave', 'Tunnel'],
            ['Cliff', 'Ridge'],
            ['Volcano', 'Earthquake'],
            ['Tide', 'Wave'],
            ['Sand', 'Dirt'],
            ['Rainbow', 'Aurora'],
            ['Sunny', 'Cloudy'],
            ['Warm', 'Cold'],
            ['Hot', 'Cool'],
            ['Wet', 'Dry'],
            ['Windy', 'Calm'],
            ['Clear', 'Overcast'],
            ['Thunderstorm', 'Hailstorm'],
            ['Drizzle', 'Downpour'],
            ['Dew', 'Frost'],
            ['Frost', 'Ice'],
            ['Hail', 'Sleet'],
            ['Blizzard', 'Whirlwind'],
            ['Breeze', 'Gale'],
            ['Humidity', 'Dryness'],
            ['Barometric Pressure', 'Temperature'],
            ['Seasons', 'Months'],
            ['Day', 'Night'],
            ['Morning', 'Evening'],
            ['Dusk', 'Dawn'],
            ['Twilight', 'Midnight'],
            ['Peak', 'Summit'],
            ['Ridge', 'Slope'],
            ['Vale', 'Gorge'],
            ['Cove', 'Bay'],
            ['Strait', 'Channel'],
            ['Водопад', 'Rapids'],
            ['Geyser', 'Hot Spring'],
            ['Oasis', 'Spring'],
            ['Marsh', 'Swamp'],
            ['Bog', 'Fen'],
            ['Яadow', 'Prairie'],
            ['Savanna', 'Steppe'],
            ['Tundra', 'Permafrost'],
            ['Plateau', 'Basin'],
            ['Delta', 'Estuary'],
            ['Coral Reef', 'Kelp Forest'],
            ['Trench', 'Ridge'],
            ['Glacier', 'Iceberg'],
            ['Geode', 'Crystal'],
            ['Pebble', 'Gravel'],
            ['Limestone', 'Granite'],
            ['Sandstone', 'Shale'],
            ['Cedar', 'Oak'],
            ['Pine', 'Birch'],
            ['Fern', 'Moss'],
            ['Ridge', 'Vale'],
            ['Plateau', 'Basin'],
            ['Cove', 'Bay'],
            ['Strait', 'Channel'],
            ['Водопад', 'Rapids'],
            ['Geyser', 'Spring'],
            ['Marsh', 'Swamp'],
            ['Prairie', 'Яadow'],
            ['Savanna', 'Steppe'],
            ['Tundra', 'Taiga'],
            ['Delta', 'Estuary'],
            ['Coral Reef', 'Kelp Forest'],
            ['Glacier', 'Iceberg'],
            ['Volcano', 'Mountain'],
            ['Cave', 'Cavern'],
            ['Canyon', 'Gorge'],
            ['Водопад', 'Stream'],
            ['Lake', 'Pond'],
            ['Ocean', 'Sea'],
            ['River', 'Creek'],
            ['Beach', 'Shore'],
            ['Desert', 'Dune'],
            ['Forest', 'Woods'],
            ['Jungle', 'Rainforest'],
            ['Яadow', 'Pasture'],
            ['Hill', 'Ridge'],
            ['Plain', 'Plateau'],
            ['Soil', 'Dirt'],
            ['Rock', 'Boulder'],
            ['Stone', 'Pebble'],
            ['Soil', 'Sand'],
            ['Clay', 'Mud'],
            ['Cloud', 'Mist'],
            ['Thunder', 'Lightning'],
            ['Stream', 'Brook']
        ],
        'Funny': [
            ['Pee', 'Lemonade'],
            ['Poop', 'Brownie'],
            ['Snot', 'Cottage Cheese'],
            ['Spit', 'Saliva'],
            ['Drool', 'Jelly'],
            ['Fart', 'Wind'],
            ['Burp', 'Hiccup'],
            ['Dandruff', 'Snow'],
            ['Sweat', 'Dew'],
            ['Booger', 'Candy'],
            ['Zit', 'Pimple'],
            ['Wrinkle', 'Fold'],
            ['Baldness', 'Shine'],
            ['Armpit', 'Underarm'],
            ['Belly Button', 'Navel'],
            ['Dimple', 'Indent'],
            ['Freckle', 'Spot'],
            ['Mole', 'Wart'],
            ['Scar', 'Mark'],
            ['Bruise', 'Boo-boo'],
            ['Rash', 'Irritation'],
            ['Blush', 'Flush'],
            ['Tear', 'Cry'],
            ['Saliva', 'Juice'],
            ['Mucus', 'Goo'],
            ['Stubble', 'Prickle'],
            ['Eyebrow', 'Caterpillar'],
            ['Eyelash', 'Feather'],
            ['Hair', 'Strand'],
            ['Nail', 'Claw'],
            ['Toe', 'Digit'],
            ['Belly', 'Tummy'],
            ['Chin', 'Jaw'],
            ['Cheek', 'Chubby'],
            ['Lip', 'Mouth'],
            ['Tongue', 'Licker'],
            ['Tooth', 'Fang'],
            ['Ear', 'Lobe'],
            ['Eye', 'Peeper'],
            ['Nose', 'Schnoz'],
            ['Yawn', 'Tired'],
            ['Snore', 'Sleep'],
            ['Shiver', 'Cold'],
            ['Twitch', 'Jump'],
            ['Hiccup', 'Gulp'],
            ['Sneeze', 'Bless Ты'],
            ['Cough', 'Sick'],
            ['Goosebump', 'Scared'],
            ['Muscle', 'Strong'],
            ['Fat', 'Heavy'],
            ['Bone', 'Skeleton'],
            ['Blood', 'Red'],
            ['Skin', 'Outside'],
            ['Vein', 'Blue Line'],
            ['Scar', 'Cut Mark'],
            ['Bump', 'Lump'],
            ['Bruise', 'Black Eye'],
            ['Rash', 'Red Spot'],
            ['Spot', 'Dot'],
            ['Sunburn', 'Hot'],
            ['Tan', 'Brown'],
            ['Pale', 'White'],
            ['Pimple', 'Zit'],
            ['Wrinkle', 'Line'],
            ['Freckle', 'Dot'],
            ['Sweat', 'Wet'],
            ['Wiggle', 'Dance'],
            ['Bounce', 'Jump'],
            ['Tickle', 'Laugh'],
            ['Poke', 'Poke'],
            ['Pinch', 'Grab'],
            ['Pull', 'Drag'],
            ['Push', 'Shove'],
            ['Kick', 'Leg Attack'],
            ['Slap', 'Hit'],
            ['Punch', 'Fist'],
            ['Пропустить', 'Hop'],
            ['Run', 'Sprint'],
            ['Walk', 'Step'],
            ['Sit', 'Squat'],
            ['Spin', 'Twirl']
        ],
        'Sports & Fitness': [
            ['Yoga', 'Pilates'],
            ['Marathon', 'Sprint'],
            ['Gym', 'Fitness Center'],
            ['Treadmill', 'Bike'],
            ['Dumbbells', 'Barbells'],
            ['Pushup', 'Situp'],
            ['Protein Shake', 'Energy Drink'],
            ['Yoga Mat', 'Exercise Mat'],
            ['Running Shoes', 'Training Shoes'],
            ['Squat', 'Lunge'],
            ['Cardio', 'Strength Training'],
            ['Personal Trainer', 'Coach'],
            ['Stretching', 'Warming Up'],
            ['Bench Press', 'Chest Press'],
            ['Burpee', 'Jump Squat'],
            ['Plank', 'Bridge'],
            ['Cycling', 'Spinning'],
            ['CrossFit', 'Boot Camp'],
            ['Boxing', 'Kickboxing'],
            ['Jump Rope', 'Пропуститьping'],
            ['Pull Up', 'Chin Up'],
            ['Deadlift', 'Clean and Jerk'],
            ['Sports Bra', 'Tank Top'],
            ['Water Bottle', 'Shaker'],
            ['Resistance Band', 'Weight Belt'],
            ['Foam Roller', 'Massage Ball'],
            ['Fitness Tracker', 'Smartwatch'],
            ['Recovery', 'Rest Day'],
            ['Muscle Gain', 'Weight Loss'],
            ['Rep', 'Set'],
            ['Jogging', 'Running'],
            ['Abs', 'Core'],
            ['Biceps', 'Triceps'],
            ['Rowing', 'Kayaking'],
            ['Climbing', 'Bouldering'],
            ['Zumba', 'Aerobics'],
            ['HIIT', 'Circuit Training'],
            ['Kettlebell', 'Яdicine Ball'],
            ['Leg Press', 'Calf Raise'],
            ['Shoulder Press', 'Lateral Raise'],
            ['Crunch', 'Leg Raise'],
            ['Mountain Climber', 'High Knees'],
            ['Wall Sit', 'Squat Hold'],
            ['Rowing Machine', 'Elliptical'],
            ['Protein Bar', 'Energy Bar'],
            ['Pre-Workout', 'Post-Workout'],
            ['Bulk', 'Cut'],
            ['Gym Bag', 'Duffel Bag'],
            ['Sneakers', 'Cleats'],
            ['Sweatband', 'Headband'],
            ['Jogging', 'Sprinting'],
            ['Walking', 'Running'],
            ['Swimming', 'Diving'],
            ['Tennis', 'Squash'],
            ['Badminton', 'Volleyball'],
            ['Weightlifting', 'Bodybuilding'],
            ['Stretching', 'Flexibility'],
            ['Cardio', 'Aerobics'],
            ['Strength Training', 'Resistance Training'],
            ['Sprinting', 'Endurance'],
            ['Agility', 'Balance'],
            ['Warm-up', 'Cool-down'],
            ['Conditioning', 'Training'],
            ['Reps', 'Sets'],
            ['Stamina', 'Endurance'],
            ['Mobility', 'Stability'],
            ['Stance', 'Posture'],
            ['Technique', 'Form'],
            ['Skill', 'Ability'],
            ['Exercise', 'Workout'],
            ['Fitness', 'Health'],
            ['Muscle', 'Strength'],
            ['Endurance', 'Stamina'],
            ['Agility', 'Speed'],
            ['Balance', 'Flexibility'],
            ['Weight Lifting', 'Strength Training'],
            ['Aerobics', 'Cardio'],
            ['Marathon', 'Race'],
            ['Competition', 'Tournament'],
            ['Victory', 'Win'],
            ['Defeat', 'Loss'],
            ['Score', 'Point'],
            ['Team', 'Squad'],
            ['Champion', 'Victor'],
            ['Loser', 'Defeated'],
            ['Trainer', 'Instructor'],
            ['Athlete', 'Competitor'],
            ['Яdal', 'Trophy'],
            ['Swimming', 'Diving'],
            ['Cycling', 'Mountain Biking'],
            ['Tennis', 'Badminton']
        ],
        'Technology & Digital': [
            ['Smartphone', 'Tablet'],
            ['WiFi', 'Bluetooth'],
            ['App', 'Software'],
            ['Email', 'Text Яssage'],
            ['Social Яdia', 'Platform'],
            ['Streaming', 'Download'],
            ['Cloud Storage', 'Hard Drive'],
            ['Password', 'PIN'],
            ['Screenshot', 'Screen Recording'],
            ['Hashtag', 'Яntion'],
            ['Like', 'Share'],
            ['Follower', 'Subscriber'],
            ['Notification', 'Alert'],
            ['Emoji', 'Sticker'],
            ['Video Call', 'Voice Call'],
            ['Browser', 'Search Engine'],
            ['Website', 'Web Page'],
            ['Upload', 'Download'],
            ['Login', 'Sign In'],
            ['Update', 'Upgrade'],
            ['Bug', 'Glitch'],
            ['AI', 'Machine Learning'],
            ['VR', 'AR'],
            ['Cryptocurrency', 'Bitcoin'],
            ['NFT', 'Digital Art'],
            ['Podcast', 'Audiobook'],
            ['E-book', 'PDF'],
            ['USB', 'SD Card'],
            ['Router', 'Modem'],
            ['Firewall', 'Antivirus'],
            ['Backup', 'Restore'],
            ['Cache', 'Cookies'],
            ['Spam', 'Junk Mail'],
            ['Folder', 'Directory'],
            ['File', 'Document'],
            ['Copy', 'Paste'],
            ['Save', 'Export'],
            ['Keyboard', 'Mouse'],
            ['Touchscreen', 'Trackpad'],
            ['Charger', 'Power Bank'],
            ['Laptop', 'Desktop'],
            ['SSD', 'HDD'],
            ['RAM', 'Яmory'],
            ['CPU', 'Processor'],
            ['GPU', 'Graphics Card'],
            ['Pixel', 'Resolution'],
            ['Refresh Rate', 'Frame Rate'],
            ['Bandwidth', 'Speed'],
            ['Server', 'Host'],
            ['Domain', 'URL'],
            ['Software', 'Hardware'],
            ['Cloud', 'Local'],
            ['Browser', 'Engine'],
            ['Server', 'Client'],
            ['Database', 'Яmory'],
            ['Network', 'Internet'],
            ['Cable', 'Wire'],
            ['Adapter', 'Converter'],
            ['Port', 'Socket'],
            ['Monitor', 'Display'],
            ['Keyboard', 'Keypad'],
            ['Mouse', 'Trackpad'],
            ['Router', 'Modem'],
            ['Firewall', 'Gateway'],
            ['Encryption', 'Decryption'],
            ['Upload', 'Download'],
            ['Sync', 'Backup'],
            ['Cache', 'Buffer'],
            ['Format', 'Convert'],
            ['Internet', 'Web'],
            ['Email', 'Яssage'],
            ['Chat', 'Text'],
            ['Video', 'Film'],
            ['Photo', 'Picture'],
            ['File', 'Document'],
            ['Folder', 'Directory'],
            ['Screen', 'Monitor'],
            ['Computer', 'PC'],
            ['Device', 'Gadget'],
            ['Data', 'Information'],
            ['Speed', 'Connection'],
            ['Signal', 'Reception'],
            ['Battery', 'Power'],
            ['Bug', 'Glitch'],
            ['Virus', 'Malware'],
            ['Security', 'Protection'],
            ['Login', 'Password'],
            ['Account', 'Profile'],
            ['Email', 'Яssage'],
            ['Website', 'App'],
            ['Download', 'Upload']
        ],
        'Travel & Places': [
            ['Airport', 'Train Station'],
            ['Hotel', 'Hostel'],
            ['Passport', 'Visa'],
            ['Suitcase', 'Backpack'],
            ['Flight', 'Journey'],
            ['Tourist', 'Traveler'],
            ['Vacation', 'Holiday'],
            ['Cruise', 'Yacht'],
            ['Camping', 'Glamping'],
            ['Museum', 'Gallery'],
            ['Monument', 'Landmark'],
            ['City', 'Town'],
            ['Capital', 'Яtropolis'],
            ['Restaurant', 'Cafe'],
            ['Bar', 'Pub'],
            ['Mall', 'Market'],
            ['Park', 'Plaza'],
            ['Zoo', 'Aquarium'],
            ['Temple', 'Church'],
            ['Casino', 'Resort'],
            ['Beach Resort', 'Ski Resort'],
            ['Souvenir', 'Gift'],
            ['Map', 'GPS'],
            ['Tour Guide', 'Travel Agent'],
            ['Boarding Pass', 'Ticket'],
            ['Check-in', 'Check-out'],
            ['Jet Lag', 'Time Zone'],
            ['Foreign Currency', 'Exchange Rate'],
            ['Duty Free', 'Tax Refund'],
            ['Itinerary', 'Travel Plan'],
            ['Taxi', 'Uber'],
            ['Bus', 'Tram'],
            ['Subway', 'Яtro'],
            ['Ferry', 'Boat'],
            ['Rental Car', 'Lease'],
            ['Motel', 'Inn'],
            ['Airbnb', 'Homestay'],
            ['Boutique Hotel', 'Luxury Hotel'],
            ['Buffet', 'A la Carte'],
            ['Street Food', 'Food Court'],
            ['Viewpoint', 'Observation Deck'],
            ['Beach', 'Coastline'],
            ['Mountain', 'Peak'],
            ['Valley', 'Gorge'],
            ['Desert', 'Oasis'],
            ['Rainforest', 'Jungle'],
            ['Cathedral', 'Mosque'],
            ['Palace', 'Castle'],
            ['Statue', 'Sculpture'],
            ['Bridge', 'Tower'],
            ['Museum', 'Gallery'],
            ['Restaurant', 'Cafe'],
            ['Bar', 'Pub'],
            ['Market', 'Mall'],
            ['Park', 'Square'],
            ['Zoo', 'Aquarium'],
            ['Temple', 'Church'],
            ['Mosque', 'Synagogue'],
            ['Castle', 'Palace'],
            ['Fortress', 'Citadel'],
            ['Monastery', 'Convent'],
            ['Theater', 'Cinema'],
            ['Concert Hall', 'Auditorium'],
            ['Stadium', 'Arena'],
            ['Harbor', 'Port'],
            ['Dock', 'Pier'],
            ['Bridge', 'Tunnel'],
            ['Lighthouse', 'Beacon'],
            ['Monument', 'Statue'],
            ['Building', 'Structure'],
            ['House', 'Home'],
            ['Building', 'Skyscraper'],
            ['Office', 'Workplace'],
            ['School', 'University'],
            ['Library', 'Bookstore'],
            ['Store', 'Shop'],
            ['Market', 'Bazaar'],
            ['Street', 'Road'],
            ['Highway', 'Freeway'],
            ['Path', 'Trail'],
            ['Playground', 'Park'],
            ['Garden', 'Botanical'],
            ['Walkway', 'Sidewalk'],
            ['Parking', 'Garage'],
            ['Station', 'Terminal'],
            ['Bus Stop', 'Transit'],
            ['Bench', 'Seat'],
            ['Booth', 'Stall'],
            ['Hotel', 'Motel'],
            ['Airport', 'Terminal'],
            ['Museum', 'Gallery']
        ],
        'Relationships': [
            ['Boyfriend', 'Girlfriend'],
            ['Husband', 'Wife'],
            ['Dating', 'Courting'],
            ['First Date', 'Blind Date'],
            ['Love', 'Crush'],
            ['Valentine', 'Anniversary'],
            ['Proposal', 'Engagement'],
            ['Wedding', 'Marriage'],
            ['Honeymoon', 'Vacation'],
            ['Romance', 'Passion'],
            ['Flirting', 'Teasing'],
            ['Breakup', 'Divorce'],
            ['Ex', 'Former'],
            ['Single', 'Available'],
            ['Commitment', 'Relationship'],
            ['Trust', 'Loyalty'],
            ['Jealousy', 'Envy'],
            ['Argument', 'Fight'],
            ['Makeup', 'Reconcile'],
            ['Soulmate', 'Twin Flame'],
            ['Friend Zone', 'Rejected'],
            ['Chemistry', 'Connection'],
            ['Red Flag', 'Deal Breaker'],
            ['Toxic', 'Unhealthy'],
            ['Supportive', 'Caring'],
            ['Cheating', 'Affair'],
            ['Long Distance', 'Remote'],
            ['Exclusive', 'Committed'],
            ['Casual', 'Serious'],
            ['Moving In', 'Cohabiting'],
            ['Partner', 'Significant Other'],
            ['Bae', 'Sweetheart'],
            ['Fiancé', 'Fiancée'],
            ['Newlyweds', 'Just Married'],
            ['Date Night', 'Quality Time'],
            ['Kiss', 'Hug'],
            ['Hold Hands', 'Cuddle'],
            ['Compliment', 'Flattery'],
            ['Gift', 'Surprise'],
            ['Flowers', 'Chocolates'],
            ['Love Letter', 'Text Яssage'],
            ['Miss Ты', 'Thinking of Ты'],
            ['Butterflies', 'Heart Racing'],
            ['Spark', 'Vibe'],
            ['Talking Stage', 'Getting to Know'],
            ['Official', 'Going Steady'],
            ['Open Relationship', 'Polyamory'],
            ['Trial Separation', 'Break'],
            ['Closure', 'Moving On'],
            ['Rebound', 'Fling'],
            ['Partner', 'Companion'],
            ['Lover', 'Sweetheart'],
            ['Spouse', 'Напарник'],
            ['Fiancé', 'Fiancée'],
            ['Newlywed', 'Just Married'],
            ['Admirer', 'Suitor'],
            ['Crush', 'Infatuation'],
            ['Attraction', 'Chemistry'],
            ['Affection', 'Devotion'],
            ['Companion', 'Напарник'],
            ['Soulmate', 'Twin Flame'],
            ['Darling', 'Honey'],
            ['Love', 'Adore'],
            ['Cherish', 'Treasure'],
            ['Admiration', 'Respect'],
            ['Connection', 'Bond'],
            ['Intimacy', 'Closeness'],
            ['Romance', 'Passion'],
            ['Tenderness', 'Affection'],
            ['Date', 'Outing'],
            ['Kiss', 'Embrace'],
            ['Hold', 'Hug'],
            ['Touch', 'Caress'],
            ['Look', 'Gaze'],
            ['Smile', 'Laugh'],
            ['Talk', 'Discuss'],
            ['Listen', 'Hear'],
            ['Share', 'Tell'],
            ['Promise', 'Vow'],
            ['Forgive', 'Forget'],
            ['Support', 'Comfort'],
            ['Understand', 'Empathize'],
            ['Connect', 'Bond'],
            ['Attract', 'Charm'],
            ['Respect', 'Honor'],
            ['Admire', 'Adore'],
            ['Miss', 'Long For'],
            ['Belong', 'Together'],
            ['Brother', 'Sister'],
            ['Parent', 'Guardian'],
            ['Partner', 'Companion']
        ],
        'Brands & Companies': [
            ['Apple', 'Samsung'],
            ['Nike', 'Adidas'],
            ['McDonald\'s', 'Burger King'],
            ['Coca-Cola', 'Pepsi'],
            ['Starbucks', 'Costa'],
            ['Google', 'Bing'],
            ['Facebook', 'Instagram'],
            ['ТыTube', 'TikTok'],
            ['Amazon', 'eBay'],
            ['Netflix', 'Disney+'],
            ['Spotify', 'Apple Music'],
            ['PlayStation', 'Xbox'],
            ['iPhone', 'Android'],
            ['Windows', 'Mac'],
            ['Tesla', 'BMW'],
            ['Яrcedes', 'Audi'],
            ['Toyota', 'Honda'],
            ['Ford', 'Chevrolet'],
            ['IKEA', 'HomeDepot'],
            ['Walmart', 'Target'],
            ['Louis Vuitton', 'Gucci'],
            ['Rolex', 'Omega'],
            ['Mastercard', 'Visa'],
            ['Uber', 'Lyft'],
            ['Airbnb', 'Booking.com'],
            ['Subway', 'Chipotle'],
            ['KFC', 'Popeyes'],
            ['Pizza Hut', 'Domino\'s'],
            ['H&M', 'Zara'],
            ['Lego', 'Playmobil'],
            ['Twitter', 'X'],
            ['WhatsApp', 'Telegram'],
            ['Zoom', 'Teams'],
            ['Slack', 'Discord'],
            ['Reddit', 'Tumblr'],
            ['Twitch', 'Mixer'],
            ['Snapchat', 'BeReal'],
            ['LinkedIn', 'Indeed'],
            ['PayPal', 'Venmo'],
            ['Stripe', 'Square'],
            ['FedEx', 'UPS'],
            ['DHL', 'USPS'],
            ['Porsche', 'Ferrari'],
            ['Lamborghini', 'Bugatti'],
            ['Lexus', 'Infiniti'],
            ['Volkswagen', 'Mazda'],
            ['Chanel', 'Dior'],
            ['Prada', 'Versace'],
            ['Armani', 'Burberry'],
            ['Cartier', 'Tiffany'],
            ['Rolex', 'Omega'],
            ['Porsche', 'Ferrari'],
            ['Lamborghini', 'Bugatti'],
            ['Gucci', 'Louis Vuitton'],
            ['Dior', 'Prada'],
            ['Versace', 'Armani'],
            ['Burberry', 'Chanel'],
            ['Hermès', 'Balenciaga'],
            ['Dolce Gabbana', 'Givenchy'],
            ['Fendi', 'Valentino'],
            ['Ralph Lauren', 'Tommy Hilfiger'],
            ['Calvin Klein', 'Diesel'],
            ['Hugo Boss', 'Lacoste'],
            ['Polo', 'Gap'],
            ['Zara', 'H&M'],
            ['ASOS', 'Shein'],
            ['Forever 21', 'Urban Outfitters'],
            ['Target', 'Walmart'],
            ['Costco', 'BJ Wholesale'],
            ['Crocs', 'Timberland'],
            ['Sketchers', 'New Balance'],
            ['Puma', 'Reebok'],
            ['Converse', 'Vans'],
            ['Birkenstock', 'Clarks'],
            ['Gucci', 'Coach'],
            ['Michael Kors', 'Kate Spade'],
            ['Fossil', 'Bulova'],
            ['Swatch', 'Timex'],
            ['Canon', 'Nikon'],
            ['Sony', 'Panasonic'],
            ['LG', 'Samsung'],
            ['Philips', 'Dyson'],
            ['Electrolux', 'Whirlpool'],
            ['Microsoft', 'Apple'],
            ['Google', 'Yahoo'],
            ['Facebook', 'Twitter'],
            ['TikTok', 'Instagram'],
            ['Airbnb', 'Booking'],
            ['Netflix', 'Hulu'],
            ['Tesla', 'Toyota'],
            ['Amazon', 'eBay']
        ],
        'Historical Figures': [
            ['Napoleon', 'Caesar'],
            ['Einstein', 'Newton'],
            ['Gandhi', 'Mandela'],
            ['Lincoln', 'Washington'],
            ['Shakespeare', 'Dickens'],
            ['Beethoven', 'Mozart'],
            ['Leonardo da Vinci', 'Michelangelo'],
            ['Picasso', 'Van Gogh'],
            ['Marie Curie', 'Rosalind Franklin'],
            ['Cleopatra', 'Nefertiti'],
            ['Churchill', 'Roosevelt'],
            ['Joan of Arc', 'Boudica'],
            ['Marco Polo', 'Columbus'],
            ['Darwin', 'Galileo'],
            ['Socrates', 'Plato'],
            ['Alexander the Great', 'Genghis Khan'],
            ['Queen Victoria', 'Queen Elizabeth'],
            ['Martin Luther King', 'Rosa Parks'],
            ['Helen Keller', 'Anne Frank'],
            ['Mother Teresa', 'Princess Diana'],
            ['Karl Marx', 'Adam Smith'],
            ['Freud', 'Jung'],
            ['Tesla', 'Edison'],
            ['Wright Brothers', 'Lindbergh'],
            ['Armstrong', 'Aldrin'],
            ['Homer', 'Virgil'],
            ['Buddha', 'Confucius'],
            ['Aristotle', 'Archimedes'],
            ['Copernicus', 'Kepler'],
            ['Voltaire', 'Rousseau'],
            ['Mozart', 'Bach'],
            ['Rembrandt', 'Vermeer'],
            ['Dante', 'Petrarch'],
            ['Frederick the Great', 'Peter the Great'],
            ['Catherine the Great', 'Elizabeth I'],
            ['Hannibal', 'Scipio'],
            ['Sun Tzu', 'Machiavelli'],
            ['Henry VIII', 'Louis XIV'],
            ['Charlemagne', 'Otto the Great'],
            ['Saladin', 'Richard the Lionheart'],
            ['Attila the Hun', 'Tamerlane'],
            ['Spartacus', 'Braveheart'],
            ['Harriet Tubman', 'Sojourner Правда'],
            ['Susan B. Anthony', 'Elizabeth Cady Stanton'],
            ['Florence Nightingale', 'Clara Barton'],
            ['Amelia Earhart', 'Bessie Coleman'],
            ['Christopher Columbus', 'Vasco da Gama'],
            ['Magellan', 'Cook'],
            ['Lewis and Clark', 'Shackleton'],
            ['Neil Armstrong', 'Yuri Gagarin'],
            ['Cleopatra', 'Julius Caesar'],
            ['Montezuma', 'Aztec Emperor'],
            ['Alexander', 'Darius'],
            ['Hammurabi', 'Nebuchadnezzar'],
            ['Pharaoh', 'Dynasty'],
            ['Sultan', 'Caliph'],
            ['Czar', 'Tsar'],
            ['King', 'Emperor'],
            ['Queen', 'Princess'],
            ['Duke', 'Earl'],
            ['Baron', 'Count'],
            ['Lord', 'Noble'],
            ['Prince', 'Regent'],
            ['Monarch', 'Ruler'],
            ['Dictator', 'Tyrant'],
            ['Conqueror', 'Warlord'],
            ['General', 'Admiral'],
            ['Strategist', 'Tactician'],
            ['Warrior', 'Soldier'],
            ['Emperor', 'King'],
            ['Empress', 'Queen'],
            ['Prince', 'Duke'],
            ['Princess', 'Duchess'],
            ['Saint', 'Prophet'],
            ['Philosopher', 'Scholar'],
            ['Explorer', 'Navigator'],
            ['Inventor', 'Engineer'],
            ['Artist', 'Sculptor'],
            ['Composer', 'Musician'],
            ['Author', 'Poet'],
            ['Actress', 'Actor'],
            ['Dancer', 'Performer'],
            ['Athlete', 'Champion'],
            ['Knight', 'Noble'],
            ['Peasant', 'Commoner'],
            ['Slave', 'Servant'],
            ['Free', 'Liberated'],
            ['Independent', 'Self-Made'],
            ['King', 'Emperor'],
            ['Queen', 'Princess'],
            ['Warrior', 'Soldier']
        ],
        'Movies': [
            ['Titanic', 'Avatar'],
            ['Inception', 'Interstellar'],
            ['The Matrix', 'The Dark Knight'],
            ['Frozen', 'Moana'],
            ['Shrek', 'Toy Story'],
            ['Spider-Man', 'Batman'],
            ['Iron Man', 'Captain America'],
            ['Joker', 'Thanos'],
            ['Harry Potter', 'Lord of the Rings'],
            ['Jurassic Park', 'King Kong'],
            ['The Avengers', 'The Justice League'],
            ['Back to the Future', 'Terminator'],
            ['Jaws', 'Alien'],
            ['Gladiator', 'Braveheart'],
            ['The Godfather', 'Scarface'],
            ['Pulp Fiction', 'Reservoir Dogs'],
            ['The Sixth Sense', 'The Others'],
            ['Forrest Gump', 'Life Is Beautiful'],
            ['The Shawshank Redemption', 'The Green Mile'],
            ['Saving Private Ryan', 'Dunkirk'],
            ['Top Gun', 'Maverick'],
            ['Rocky', 'Rambo'],
            ['The Sound of Music', 'Grease'],
            ['Dirty Dancing', 'La La Land'],
            ['Cinderella', 'Sleeping Beauty'],
            ['Finding Nemo', 'The Lion King'],
            ['Paddington', 'Winnie the Pooh'],
            ['Gremlins', 'Poltergeist'],
            ['The Ring', 'Insidious'],
            ['Scream', 'A Nightmare on Elm Street'],
            ['Dune', 'Star Wars'],
            ['Avatar 2', 'Avatar 3'],
            ['The Conjuring', 'Sinister'],
            ['It', 'Us'],
            ['Get Out', 'Hereditary'],
            ['Oppenheimer', 'The Imitation Game'],
            ['Barbie', 'Oppenheimer'],
            ['Dune Part Two', 'Rebel Moon'],
            ['Guardians of the Galaxy', 'Thor'],
            ['Доктор Strange', 'Black Panther'],
            ['Deadpool', 'Wolverine'],
            ['The Fast and Furious', 'Mission Impossible'],
            ['James Bond', 'Jason Bourne'],
            ['John Wick', 'The Man from Toronto'],
            ['Oppenheimer', 'Killers of the Flower Moon'],
            ['Once Upon a Time in Hollywood', 'The Wolf of Wall Street'],
            ['Inception', 'Яmento'],
            ['The Usual Suspects', 'Se7en'],
            ['Parasite', 'Train to Busan'],
            ['Everything Everywhere All at Once', 'The Banshees of Inisherin'],
            ['Dune', 'Dune Яssiah'],
            ['Barbenheimer', 'Oppenheimer'],
            ['Dungeons & Dragons', 'The Quest'],
            ['Sound of Freedom', 'Unbroken'],
            ['Killers of the Flower Moon', 'Scorsese'],
            ['Past Lives', 'Nimona'],
            ['Society of the Snow', 'Expedition'],
            ['Dream Scenario', 'Nightmare'],
            ['Talk to Я', 'M3GAN'],
            ['Insidious', 'Sinister'],
            ['Five Nights at Freddy\'s', 'Fnaf'],
            ['Napoleon', 'Historical'],
            ['The Zone of Interest', 'Dark'],
            ['Passages', 'Love Story'],
            ['The Iron Claw', 'Wrestling'],
            ['Priscilla', 'Elvis'],
            ['American Fiction', 'Comedy'],
            ['Killers of the Flower Moon', 'Crime'],
            ['Indiana Jones', 'Adventure'],
            ['Mission Impossible', 'Action'],
            ['James Bond', 'Jason Bourne'],
            ['Fast & Furious', 'Lethal Weapon'],
            ['Die Hard', 'Arnold Schwarzenegger'],
            ['Terminator', 'Robocop'],
            ['Superman', 'Batman'],
            ['Captain America', 'Iron Man'],
            ['Thor', 'Hulk'],
            ['Доктор Strange', 'Black Panther'],
            ['Shrek', 'Shriek'],
            ['Toy Story', 'Bugs Life'],
            ['Finding Nemo', 'Sharkslayer'],
            ['Frozen', 'Tangled'],
            ['Moana', 'Encanto'],
            ['Pixar', 'DreamWorks'],
            ['Animated', 'CGI'],
            ['Thriller', 'Suspense'],
            ['Drama', 'Comedy'],
            ['Horror', 'Terror'],
            ['Adventure', 'Expedition'],
            ['Sci-Fi', 'Fantasy'],
            ['Western', 'Cowboy'],
            ['Детектив', 'Mystery'],
            ['Spy', 'Thriller'],
            ['Heist', 'Crime'],
            ['Love Story', 'Romance'],
            ['Animation', 'Cartoon'],
            ['Documentary', 'Biopic'],
            ['Action Scene', 'Stunts'],
            ['Plot', 'Story'],
            ['Dialogue', 'Monologue'],
            ['Scene', 'Shot'],
            ['Director', 'Producer'],
            ['Actor', 'Actress'],
            ['Blockbuster', 'Box Office'],
            ['Premiere', 'Release'],
            ['Review', 'Critique'],
            ['Rating', 'Score'],
            ['Favorite', 'Fan Favorite'],
            ['Avatar', 'Transformer'],
            ['Titanic', 'Poseidon'],
            ['Frozen', 'Tangled']
        ],
        'Internet Slang': [
            ['YOLO', 'FOMO'],
            ['LOL', 'ROFL'],
            ['OMG', 'WTF'],
            ['Salty', 'Mad'],
            ['Ghosting', 'Benching'],
            ['Catfishing', 'Phishing'],
            ['Bae', 'Bro'],
            ['Stan', 'Simp'],
            ['GOAT', 'NOOB'],
            ['Sus', 'Vibe Check'],
            ['Slay', 'Flex'],
            ['Snatched', 'Lit'],
            ['Lowkey', 'Highkey'],
            ['Spill the Tea', 'Shade'],
            ['Bye Felicia', 'Periodt'],
            ['Salty', 'Petty'],
            ['Karen', 'Chad'],
            ['Simp', 'Incel'],
            ['Deep Fake', 'Doomscrolling'],
            ['Яme', 'Viral'],
            ['Trend', 'Trending'],
            ['Dox', 'Raid'],
            ['Troll', 'Stir the Pot'],
            ['Яme Lord', 'Content Creator'],
            ['Ship', 'Slash'],
            ['Fan Fic', 'Canon'],
            ['Cringe', 'Awkward'],
            ['Based', 'Ratio'],
            ['No Cap', 'Cap'],
            ['Bussin', 'Smackin'],
            ['NPC', 'Main Character'],
            ['Vibes', 'Energy'],
            ['Tea', 'Gossip'],
            ['Periodt', 'Period'],
            ['Slaps', 'Bops'],
            ['Hits Different', 'Underrated'],
            ['It\'s Giving', 'Main Villain'],
            ['Ick', 'Turn-off'],
            ['Obsessed', 'Triggered'],
            ['Salty', 'Pissed'],
            ['Threw', 'Failed'],
            ['Mid', 'Weak'],
            ['Fire', 'Heat'],
            ['Drip', 'Swag'],
            ['Vibe', 'Mood'],
            ['Receipts', 'Proof'],
            ['Read', 'Clap Back'],
            ['Subtle', 'In Тыr Face'],
            ['Call Out Culture', 'Cancel Culture'],
            ['Stan Twitter', 'Fandom'],
            ['Fanbase', 'Community'],
            ['Discourse', 'Drama'],
            ['Ghosted', 'Benched'],
            ['Friend Zone', 'Simping'],
            ['Uwu', 'OwO'],
            ['Edgy', 'Cringe'],
            ['Wholesome', 'Wholesome 100'],
            ['Certified Hood Classic', 'Lost to the Straights'],
            ['Caught in 4K', 'Snitches Get Stitches'],
            ['Not Я', 'If Ты Know What I Яan'],
            ['It Is What It Is', 'Periodt Queen'],
            ['Bussin No Cap', 'On Periodt'],
            ['Respectfully', 'Disrespectfully'],
            ['Go Off King', 'Go Off Queen'],
            ['Serving Face', 'Serving Looks'],
            ['Giving', 'Serving'],
            ['Cunty', 'Fierce'],
            ['Sickening', 'Stunning'],
            ['Toot', 'Boot'],
            ['Read', 'Roasted'],
            ['Snatched', 'Serving'],
            ['Lit', 'Fire'],
            ['Slaps', 'Bops'],
            ['Hits Different', 'Underrated'],
            ['It\'s Giving', 'Main Character'],
            ['Ick', 'Vibe'],
            ['Obsessed', 'Triggered'],
            ['Salty', 'Petty'],
            ['Threw', 'Failed'],
            ['Mid', 'Weak'],
            ['Drip', 'Swag'],
            ['Vibe', 'Mood'],
            ['Receipts', 'Proof'],
            ['Read', 'Clap Back'],
            ['Call Out Culture', 'Cancel Culture'],
            ['Stan Twitter', 'Fanbase'],
            ['Discourse', 'Drama'],
            ['Ghosted', 'Benched'],
            ['Friend Zone', 'Simping'],
            ['Uwu', 'OwO'],
            ['Vibe', 'Energy'],
            ['Flex', 'Flex'],
            ['Slay', 'Slayer'],
            ['Lit', 'Fire'],
            ['Dope', 'Cool'],
            ['Sick', 'Awesome'],
            ['Sick', 'Nasty'],
            ['Tight', 'Dope'],
            ['Bomb', 'Epic'],
            ['Bae', 'Boo'],
            ['Fam', 'Crew'],
            ['Bestie', 'BFF'],
            ['Salty', 'Bitter'],
            ['Extra', 'Extra'],
            ['Mood', 'Vibe'],
            ['Salty', 'Bitter'],
            ['Jelly', 'Jealous'],
            ['Stan', 'Support'],
            ['Shade', 'Insult'],
            ['Яme', 'Viral'],
            ['Hashtag', 'Trending'],
            ['Selfie', 'Photobomb']
        ],
    }
};

// Check if user has premium access
async function isPremiumUser() {
    // Use the global authManager to check premium status
    if (window.authManager) {
        return await window.authManager.checkUserPremiumStatus();
    }
    return false;
}

async function startGame() {
    const playerCount = parseInt(document.getElementById('playerCount').value);
    const undercoverCount = parseInt(document.getElementById('undercoverCount').value);
    const whiteCount = parseInt(document.getElementById('whiteCount').value);
    const useCustomWords = document.getElementById('useCustomWords').checked;
    const selectedCategory = document.getElementById('categorySelect').value;

    if (undercoverCount + whiteCount >= playerCount) {
        alert('Too many undercover and Mr. White players!');
        return;
    }

    // Initialize players
    gameState.players = Array(playerCount).fill('Civilian');

    // Set words based on custom input or random selection
    if (useCustomWords) {
        const civilianWord = document.getElementById('customCivilianWord').value.trim();
        const undercoverWord = document.getElementById('customUndercoverWord').value.trim();

        if (!civilianWord || !undercoverWord) {
            alert('Please enter both civilian and undercover words');
            return;
        }

        gameState.civilianWord = civilianWord;
        gameState.undercoverWord = undercoverWord;
    } else {
        let availableWordPairs = [];

        if (selectedCategory === 'all') {
            // Combine all categories
            Object.values(gameState.wordsByCategory).forEach(categoryPairs => {
                availableWordPairs = availableWordPairs.concat(categoryPairs);
            });
        } else {
            // Use specific category
            if (gameState.wordsByCategory[selectedCategory]) {
                availableWordPairs = gameState.wordsByCategory[selectedCategory];
            }
        }

        if (availableWordPairs.length === 0) {
            alert('No word pairs available for the selected category!');
            return;
        }

        const wordPair = availableWordPairs[Math.floor(Math.random() * availableWordPairs.length)];
        gameState.civilianWord = wordPair[0];
        gameState.undercoverWord = wordPair[1];
    }

    // Assign undercover players
    for (let i = 0; i < undercoverCount; i++) {
        let index;
        do {
            index = Math.floor(Math.random() * playerCount);
        } while (gameState.players[index] !== 'Civilian');
        gameState.players[index] = 'Undercover';
    }

    // Assign Mr. White players
    for (let i = 0; i < whiteCount; i++) {
        let index;
        do {
            index = Math.floor(Math.random() * playerCount);
        } while (gameState.players[index] !== 'Civilian');
        gameState.players[index] = 'Mr. White';
    }

    document.getElementById('setup-section').classList.add('hidden');
    document.getElementById('word-section').classList.remove('hidden');
    showWord();
}

function showWord() {
    const playerNum = gameState.currentИгрок + 1;
    document.getElementById('currentИгрок').textContent = playerNum;

    let word;
    const playerRole = gameState.players[gameState.currentИгрок];
    if (playerRole === 'Civilian') {
        word = gameState.civilianWord;
    } else if (playerRole === 'Undercover') {
        word = gameState.undercoverWord;
    } else { // Mr. White
        word = 'Blank Card';
    }

    document.getElementById('wordDisplay').textContent = word;

    // Reset flip card state
    const flipCard = document.querySelector('.flip-card');
    flipCard.classList.remove('flipped');

    // Remove previous event listeners
    const newFlipCard = flipCard.cloneNode(true);
    flipCard.parentNode.replaceChild(newFlipCard, flipCard);

    // Add new click event listener for simple toggle
    newFlipCard.addEventListener('click', function () {
        this.classList.toggle('flipped');
    });

    // Always show "Дальше Игрок" button
    document.querySelector('button[onclick="nextИгрок()"]').style.display = 'inline-block';
}

function nextИгрок() {
    gameState.currentИгрок++;
    if (gameState.currentИгрок >= gameState.players.length) {
        startVoting();
        return;
    }
    showWord();
}

function startVoting() {
    document.getElementById('word-section').classList.add('hidden');
    document.getElementById('game-section').classList.remove('hidden');
    updateИгрокList();
}

function updateИгрокList() {
    const playerList = document.getElementById('playerList');
    playerList.innerHTML = '';

    gameState.players.forEach((role, index) => {
        const playerNum = index + 1;
        const isEliminated = gameState.eliminatedИгрокs.has(index);
        const playerDiv = document.createElement('div');
        playerDiv.className = `player ${isEliminated ? 'eliminated' : ''}`;

        // Create radio button for non-eliminated players
        if (!isEliminated) {
            const radio = document.createElement('input');
            radio.type = 'radio';
            radio.name = 'playerГолос';
            radio.value = index;
            radio.id = `player${playerNum}`;
            playerDiv.appendChild(radio);

            const label = document.createElement('label');
            label.htmlFor = `player${playerNum}`;
            label.textContent = ` Игрок ${playerNum}`;
            playerDiv.appendChild(label);
        } else {
            playerDiv.textContent = `Игрок ${playerNum} (Eliminated)`;
        }

        playerList.appendChild(playerDiv);
    });
}

function eliminateИгрок() {
    const selectedИгрок = document.querySelector('input[name="playerГолос"]:checked');
    if (!selectedИгрок) {
        alert('Please select a player to eliminate!');
        return;
    }

    const eliminatedIndex = parseInt(selectedИгрок.value);
    gameState.eliminatedИгрокs.add(eliminatedIndex);

    const remainingИгрокs = gameState.players.filter((_, index) =>
        !gameState.eliminatedИгрокs.has(index)
    ).length;

    const remainingCivilians = gameState.players.filter((role, index) =>
        !gameState.eliminatedИгрокs.has(index) && role === 'Civilian'
    ).length;

    const remainingUndercover = gameState.players.filter((role, index) =>
        !gameState.eliminatedИгрокs.has(index) && role === 'Undercover'
    ).length;

    updateИгрокList();

    // Check for winners
    if (remainingИгрокs === 2) {
        // Hide eliminate button when game is over
        document.querySelector('button[onclick="eliminateИгрок()"]').style.display = 'none';

        if (remainingUndercover === 0) {
            alert('Civilians win! All undercover players have been eliminated!');
        } else if (remainingUndercover === 2) {
            alert('Undercover players win! The last two players are both undercover!');
        } else if (remainingUndercover === 1 && remainingCivilians === 1) {
            alert('Undercover player wins! They have successfully infiltrated to the end!');
        }
    }
}

function resetGame() {
    const originalWordsByCategory = gameState.wordsByCategory;
    gameState = {
        players: [],
        currentИгрок: 0,
        civilianWord: '',
        undercoverWord: '',
        eliminatedИгрокs: new Set(),
        selectedКатегории: ['Food & Drink', 'Animals', 'Objects', 'Jobs & Roles', 'Entertainment', 'Nature & Weather', 'Funny', 'Movies', 'Internet Slang'],
        wordsByCategory: originalWordsByCategory
    };

    // Show eliminate button again when game resets
    document.querySelector('button[onclick="eliminateИгрок()"]').style.display = 'inline-block';

    document.getElementById('game-section').classList.add('hidden');
    document.getElementById('word-section').classList.add('hidden');
    document.getElementById('setup-section').classList.remove('hidden');
}


// Show premium modal
function showPremiumModal() {
    document.getElementById('premium-modal').classList.remove('hidden');
}

// Close premium modal
function closePremiumModal() {
    document.getElementById('premium-modal').classList.add('hidden');
}

document.addEventListener('DOMContentLoaded', function () {
    const useCustomWordsCheckbox = document.getElementById('useCustomWords');
    const customWordsSection = document.getElementById('customWordsSection');

    useCustomWordsCheckbox.addEventListener('change', function () {
        customWordsSection.style.display = this.checked ? 'block' : 'none';
    });
});
