const gameData = {
    currentType: null,
    currentDifficulty: null,
    questions: {
        soft: { truth: [
            "In welches Tier würdest du dich verwandeln wollen?",
            "Was war deine seltsamste Kindheitsfantasie?",
            "Welches ist dein Lieblings-Emoji?",
            "Was würdest du tun, wenn du einen Tag lang unsichtbar wärst?",
            "Welcher ist dein Lieblings-Filmzitat?",
            "Was war das Langweiligste, was du je gemacht hast?",
            "Was ist deine schönste Kindheitserinnerung?",
            "Worauf bist du am meisten stolz?",
            "Wovor hast du am meisten Angst?",
            "Wer ist deine Lieblings-Cartoon-Figur?",
            "Welche Fähigkeit würdest du gerne lernen?",
            "Welche ist deine Lieblingsjahreszeit?",
            "Welche Tageszeit magst du am liebsten?",
            "Welches Haustier hättest du gerne?",
            "Welches ist dein Lieblingswetter?",
            "Welchen Freizeitpark würdest du gerne besuchen?",
            "Was ist dein Lieblings-Snack?",
            "Welchen Beruf würdest du gerne mal ausprobieren?",
            "Welcher ist dein Lieblingsduft?",
            "In welcher Art von Haus würdest du gerne wohnen?",
            "Welche Superkraft hättest du gerne?",
            "Wenn du durch die Zeit reisen könntest, was würdest du ändern?",
            "Welcher Prominente wärst du gerne für einen Tag?",
            "Wer ist deine Lieblingsfigur aus Filmen oder Serien?",
            "Welches neue Essen würdest du erfinden?",
            "Welches ist dein Lieblingsfeiertag und warum?",
            "In welcher Film- oder Serienwelt würdest du gerne leben?",
            "Wohin würdest du am liebsten reisen?",
            "Wenn du eine Sache auf der Welt ändern könntest, was wäre das?",
            "Welches war dein Lieblingsspiel als Kind?",
            "Welchen neuen Feiertag würdest du erfinden?",
            "Mit welcher historischen Person würdest du gerne sprechen?",
            "Welchen Zaubergegenstand hättest du gerne?",
            "Der Hauptcharakter welches Buches wärst du gerne?",
            "Wie würde dein Traumhaus aussehen?",
            "Welchen Film würdest du gerne drehen?",
            "Was für ein Geschäft würdest du gerne eröffnen?",
            "Welches Spiel würdest du gerne entwickeln?",
            "Was sollte dein Roboter-Assistent können?",
            "Welche neue Sportart würdest du erfinden?",
            "Was isst du am liebsten?",
            "Was trinkst du am liebsten?",
            "Welche ist deine Lieblingsfarbe?",
            "Welche Musik hörst du am liebsten?",
            "Welchen Sport machst du gerne?",
            "Welches ist dein Lieblingsbuch?",
            "Welcher ist dein Lieblingsfilm?",
            "Welche ist deine Lieblingsserie?",
            "Welches ist dein Lieblingsspiel?",
            "Welche App benutzt du am häufigsten?"
], dare: [
            "Gehe wie ein Pinguin",
            "Sprich mit einer komischen Stimme bis zur nächsten Runde",
            "Imitiere einen Prominenten bis zur nächsten Runde",
            "Trage deine Socken als Handschuhe für 5 Minuten",
            "Versuche deine eigene Nase (oder deinen Ellbogen) zu lecken",
            "Sage 10 Mal vor dem Spiegel 'Ich bin so schön/hübsch'",
            "Sprich 5 Minuten lang mit einem falschen Akzent",
            "Imitiere eine Katze mit Bewegungen und Geräuschen",
            "Imitiere einen Hund mit Bewegungen und Geräuschen",
            "Tue so, als wärst du ein Roboter",
            "Singe dein Lieblingslied wie ein Opernstar",
            "Tanze ohne Musik für 30 Sekunden",
            "Erzähle einen Witz, auch wenn er schlecht ist",
            "Mache 10 Hampelmänner",
            "Spreche 2 Minuten lang nur in Reimen",
            "Imitiere deinen Lieblingsschauspieler",
            "Mache ein Selfie mit einer lustigen Grimasse",
            "Gehe rückwärts bis zur nächsten Runde",
            "Singe das Alphabet rückwärts",
            "Stelle ein berühmtes Gemälde nach",
            "Erfinde einen neuen Tanz und führe ihn vor",
            "Erzähle eine Geschichte nur mit Handbewegungen",
            "Führe ein Schauspiel ohne Worte auf",
            "Zeichne ein Porträt von jemandem aus der Gruppe",
            "Komponiere ein kurzes Lied über das heutige Wetter",
            "Führe eine Modenschau mit deiner aktuellen Kleidung auf",
            "Bastle etwas aus den Gegenständen in der Nähe",
            "Denke dir eine neue Begrüßung aus und bringe sie allen bei",
            "Erfinde eine Kurzgeschichte mit allen Anwesenden als Charaktere",
            "Mache Tiergeräusche und lasse andere raten",
            "Erzähle jedem Anwesenden etwas Nettes",
            "Frage jemanden nach seinem Lieblingswitz",
            "Gib jemandem ein ehrliches Kompliment",
            "Teile eine peinliche Geschichte von dir",
            "Erzähle von deinem stolzesten Moment",
            "Sage jedem, was du an ihm magst",
            "Entschuldige dich bei jemandem für etwas Kleines",
            "Erzähle von einem Moment, in dem du mutig warst",
            "Teile deinen besten Ratschlag",
            "Erzähle von deinem Lieblingsfamilienmitglied",
            "Halte eine einminütige Dankesrede",
            "Führe eine Pressekonferenz über dein letztes Abenteuer",
            "Erzähle das Märchen von Rotkäppchen als Nachrichtensprecher",
            "Führe ein Bewerbungsgespräch für den Job als 'Professioneller Partygast'",
            "Halte eine Verkaufspräsentation für einen alltäglichen Gegenstand",
            "Erzähle den anderen, wie man Zähne putzt, als wäre es Raketenwissenschaft",
            "Erkläre, wie man Wasser trinkt, als wärst du ein Wissenschaftler",
            "Führe vor, wie man auf verschiedene Arten geht (traurig, glücklich, etc.)",
            "Stelle verschiedene Emotionen nur mit deinem Gesicht dar",
            "Beschreibe dein heutiges Frühstück wie ein Restaurantkritiker"
] },
        romantic: { truth: [
            "In welches Tier würdest du dich verwandeln wollen?",
            "Was war deine seltsamste Kindheitsfantasie?",
            "Welches ist dein Lieblings-Emoji?",
            "Was würdest du tun, wenn du einen Tag lang unsichtbar wärst?",
            "Welcher ist dein Lieblings-Filmzitat?",
            "Was war das Langweiligste, was du je gemacht hast?",
            "Was ist deine schönste Kindheitserinnerung?",
            "Worauf bist du am meisten stolz?",
            "Wovor hast du am meisten Angst?",
            "Wer ist deine Lieblings-Cartoon-Figur?",
            "Welche Fähigkeit würdest du gerne lernen?",
            "Welche ist deine Lieblingsjahreszeit?",
            "Welche Tageszeit magst du am liebsten?",
            "Welches Haustier hättest du gerne?",
            "Welches ist dein Lieblingswetter?",
            "Welchen Freizeitpark würdest du gerne besuchen?",
            "Was ist dein Lieblings-Snack?",
            "Welchen Beruf würdest du gerne mal ausprobieren?",
            "Welcher ist dein Lieblingsduft?",
            "In welcher Art von Haus würdest du gerne wohnen?",
            "Welche Superkraft hättest du gerne?",
            "Wenn du durch die Zeit reisen könntest, was würdest du ändern?",
            "Welcher Prominente wärst du gerne für einen Tag?",
            "Wer ist deine Lieblingsfigur aus Filmen oder Serien?",
            "Welches neue Essen würdest du erfinden?",
            "Welches ist dein Lieblingsfeiertag und warum?",
            "In welcher Film- oder Serienwelt würdest du gerne leben?",
            "Wohin würdest du am liebsten reisen?",
            "Wenn du eine Sache auf der Welt ändern könntest, was wäre das?",
            "Welches war dein Lieblingsspiel als Kind?",
            "Welchen neuen Feiertag würdest du erfinden?",
            "Mit welcher historischen Person würdest du gerne sprechen?",
            "Welchen Zaubergegenstand hättest du gerne?",
            "Der Hauptcharakter welches Buches wärst du gerne?",
            "Wie würde dein Traumhaus aussehen?",
            "Welchen Film würdest du gerne drehen?",
            "Was für ein Geschäft würdest du gerne eröffnen?",
            "Welches Spiel würdest du gerne entwickeln?",
            "Was sollte dein Roboter-Assistent können?",
            "Welche neue Sportart würdest du erfinden?",
            "Was isst du am liebsten?",
            "Was trinkst du am liebsten?",
            "Welche ist deine Lieblingsfarbe?",
            "Welche Musik hörst du am liebsten?",
            "Welchen Sport machst du gerne?",
            "Welches ist dein Lieblingsbuch?",
            "Welcher ist dein Lieblingsfilm?",
            "Welche ist deine Lieblingsserie?",
            "Welches ist dein Lieblingsspiel?",
            "Welche App benutzt du am häufigsten?"
], dare: [
            "Gehe wie ein Pinguin",
            "Sprich mit einer komischen Stimme bis zur nächsten Runde",
            "Imitiere einen Prominenten bis zur nächsten Runde",
            "Trage deine Socken als Handschuhe für 5 Minuten",
            "Versuche deine eigene Nase (oder deinen Ellbogen) zu lecken",
            "Sage 10 Mal vor dem Spiegel 'Ich bin so schön/hübsch'",
            "Sprich 5 Minuten lang mit einem falschen Akzent",
            "Imitiere eine Katze mit Bewegungen und Geräuschen",
            "Imitiere einen Hund mit Bewegungen und Geräuschen",
            "Tue so, als wärst du ein Roboter",
            "Singe dein Lieblingslied wie ein Opernstar",
            "Tanze ohne Musik für 30 Sekunden",
            "Erzähle einen Witz, auch wenn er schlecht ist",
            "Mache 10 Hampelmänner",
            "Spreche 2 Minuten lang nur in Reimen",
            "Imitiere deinen Lieblingsschauspieler",
            "Mache ein Selfie mit einer lustigen Grimasse",
            "Gehe rückwärts bis zur nächsten Runde",
            "Singe das Alphabet rückwärts",
            "Stelle ein berühmtes Gemälde nach",
            "Erfinde einen neuen Tanz und führe ihn vor",
            "Erzähle eine Geschichte nur mit Handbewegungen",
            "Führe ein Schauspiel ohne Worte auf",
            "Zeichne ein Porträt von jemandem aus der Gruppe",
            "Komponiere ein kurzes Lied über das heutige Wetter",
            "Führe eine Modenschau mit deiner aktuellen Kleidung auf",
            "Bastle etwas aus den Gegenständen in der Nähe",
            "Denke dir eine neue Begrüßung aus und bringe sie allen bei",
            "Erfinde eine Kurzgeschichte mit allen Anwesenden als Charaktere",
            "Mache Tiergeräusche und lasse andere raten",
            "Erzähle jedem Anwesenden etwas Nettes",
            "Frage jemanden nach seinem Lieblingswitz",
            "Gib jemandem ein ehrliches Kompliment",
            "Teile eine peinliche Geschichte von dir",
            "Erzähle von deinem stolzesten Moment",
            "Sage jedem, was du an ihm magst",
            "Entschuldige dich bei jemandem für etwas Kleines",
            "Erzähle von einem Moment, in dem du mutig warst",
            "Teile deinen besten Ratschlag",
            "Erzähle von deinem Lieblingsfamilienmitglied",
            "Halte eine einminütige Dankesrede",
            "Führe eine Pressekonferenz über dein letztes Abenteuer",
            "Erzähle das Märchen von Rotkäppchen als Nachrichtensprecher",
            "Führe ein Bewerbungsgespräch für den Job als 'Professioneller Partygast'",
            "Halte eine Verkaufspräsentation für einen alltäglichen Gegenstand",
            "Erzähle den anderen, wie man Zähne putzt, als wäre es Raketenwissenschaft",
            "Erkläre, wie man Wasser trinkt, als wärst du ein Wissenschaftler",
            "Führe vor, wie man auf verschiedene Arten geht (traurig, glücklich, etc.)",
            "Stelle verschiedene Emotionen nur mit deinem Gesicht dar",
            "Beschreibe dein heutiges Frühstück wie ein Restaurantkritiker"
] },
        spicy: { truth: [
            "Was ist das Peinlichste, was dir je passiert ist?",
            "Welchen Fehler bereust du am meisten?",
            "Was ist dein größtes Geheimnis?",
            "Über wen warst du schonmal eifersüchtig?",
            "Was war dein größter Vertrauensbruch?",
            "Welche Lüge erzählst du am häufigsten?",
            "Was ist deine größte Unsicherheit?",
            "Welche deiner Eigenschaften würdest du gerne ändern?",
            "Was ist dein größter Traum, den du nie jemandem erzählt hast?",
            "Wann hast du das letzte Mal geweint und warum?",
            "Welche Beziehung bereust du am meisten?",
            "Was ist das Schlechteste, was ein Freund über dich gesagt hat?",
            "Wen aus der Gruppe findest du am attraktivsten?",
            "Welchen ersten Eindruck hattest du von jedem hier?",
            "Mit wem aus der Gruppe würdest du gerne mehr Zeit verbringen?",
            "Über wen hier denkst du manchmal nach, wenn die Person nicht da ist?",
            "Welcher Charakter von jemandem hier irritiert dich am meisten?",
            "Wem hier würdest du am ehesten ein Geheimnis anvertrauen?",
            "Wen hier würdest du bei einem Zombie-Apokalypse als ersten opfern?",
            "Von wem hier würdest du dir am liebsten Rat holen?",
            "Was denkst du wirklich über dich selbst?",
            "Welche Phase deines Lebens war die schwierigste?",
            "Was ist das Mutigste, was du je getan hast?",
            "Welchen Aspekt der Gesellschaft findest du am problematischsten?",
            "Was ist deine kontroverseste Meinung?",
            "Welche Eigenschaft bewunderst du an anderen, die du nicht hast?",
            "Was ist das Selbstloseste, was du je getan hast?",
            "Welche deiner Entscheidungen hat dich am meisten geprägt?",
            "Was ist das Unethischste, was du je getan hast?",
            "Welche Erfahrung hat deine Weltanschauung am meisten verändert?",
            "Würdest du lügen, um jemandes Gefühle zu schonen?",
            "Würdest du einen kleinen Betrug begehen, wenn niemand es merken würde?",
            "Wie wichtig ist dir der gesellschaftliche Status?",
            "Was würdest du für eine Million Euro tun?",
            "Würdest du einen Tag lang das Leben von jemandem aus der Gruppe tauschen wollen?",
            "Welche gesellschaftliche Norm findest du überholt?",
            "Was denkst du über die Rolle sozialer Medien in unserem Leben?",
            "Glaubst du, dass Menschen grundsätzlich gut oder schlecht sind?",
            "Wie wichtig ist dir die Meinung anderer über dich?",
            "Würdest du deine Überzeugungen für Geld ändern?",
            "Was bereust du, nicht getan zu haben?",
            "Welchen Rat würdest du deinem jüngeren Ich geben?",
            "Was möchtest du erreicht haben, bevor du stirbst?",
            "Welche Angst hält dich am meisten zurück?",
            "Was ist dein größter innerer Konflikt?",
            "Wie stellst du dir dein Leben in 20 Jahren vor?",
            "Was würdest du anders machen, wenn du nochmal von vorn anfangen könntest?",
            "Welche Eigenschaften suchst du in einem Lebenspartner?",
            "Was ist dein dunkelster Gedanke?",
            "Welche Version von dir magst du am wenigsten?"
], dare: [
            "Entschuldige dich bei jemandem, dem du wehgetan hast",
            "Erzähle von einem Moment, in dem du jemanden enttäuscht hast",
            "Gestehe eine Lüge, die du jemandem hier erzählt hast",
            "Erzähle von einem Moment, in dem du dich geschämt hast",
            "Teile eine Angst mit, die du noch nie jemandem erzählt hast",
            "Erzähle von einer Zeit, in der du jemanden falsch eingeschätzt hast",
            "Gib zu, wann du das letzte Mal neidisch warst",
            "Erzähle von einem Moment, in dem du mutig hättest sein sollen, es aber nicht warst",
            "Teile eine Erinnerung, die dich immer noch beschäftigt",
            "Erzähle von einem Mal, als du jemand anderen verletzt hast",
            "Sage jedem hier, was du wirklich über ihn denkst (ehrlich aber respektvoll)",
            "Erzähle deine ehrliche erste Meinung über jeden hier",
            "Gib jemandem ein Kompliment, das du noch nie ausgesprochen hast",
            "Entschuldige dich bei jemandem für etwas aus der Vergangenheit",
            "Erzähle jemandem hier etwas, was du schon lange sagen wolltest",
            "Frage jemanden nach Vergebung für etwas Bestimmtes",
            "Teile mit jemandem ein Geheimnis",
            "Erzähle jemandem, wie wichtig er dir ist",
            "Sage jemandem, wofür du ihm dankbar bist",
            "Gestehe jemandem gegenüber eine Schwäche",
            "Erzähle von deinem größten persönlichen Versagen",
            "Teile eine kontroverse Meinung und erkläre, warum du so denkst",
            "Erzähle von einem Moment, der dein Leben verändert hat",
            "Beschreibe deine größte Angst vor der Zukunft",
            "Erzähle von einem Mal, als du deine Prinzipien kompromittiert hast",
            "Teile etwas mit, wofür du dich schämst",
            "Erzähle von einer schweren Entscheidung, die du treffen musstest",
            "Beschreibe einen Moment, in dem du dich völlig verloren gefühlt hast",
            "Erzähle von einer Zeit, in der du dich selbst enttäuscht hast",
            "Teile deine größte Unsicherheit mit",
            "Gestehe etwas, was du getan hast und was du für falsch hältst",
            "Erzähle von einem Mal, als du gelogen hast, um dir selbst zu helfen",
            "Teile eine Situation, in der du weggeschaut hast, obwohl du hättest handeln sollen",
            "Erzähle von einem Vorurteil, das du hattest und überwunden hast",
            "Beschreibe eine Situation, in der du unfair zu jemandem warst",
            "Erzähle von einem Mal, als du jemanden im Stich gelassen hast",
            "Teile eine Entscheidung, die du getroffen hast und die anderen geschadet hat",
            "Erzähle von einem Moment, in dem du schwach warst",
            "Beschreibe eine Situation, in der du heuchlerisch warst",
            "Erzähle von einem Mal, als du egoistisch gehandelt hast",
            "Führe ein 5-minütiges ernsthaftes Gespräch mit jemandem über eure Freundschaft",
            "Erzähle jemandem, wie er dich beeinflusst hat",
            "Teile mit der Gruppe deine tiefste Sorge über die Zukunft",
            "Sprich über ein Thema, das dir wichtig ist, aber über das du normalerweise schweigst",
            "Erzähle, welche Lektion das Leben dich am schwersten gelehrt hat",
            "Beschreibe, was Glück für dich bedeutet",
            "Erkläre, was du an der Welt ändern würdest und warum",
            "Teile deine Gedanken über den Sinn des Lebens",
            "Erzähle, was du von deinen Eltern gelernt hast (Gutes und Schlechtes)",
            "Beschreibe, wie du dir eine perfekte Welt vorstellst"
] }
    }
};
const t = { choose: "👇 Wähle euren Paar-Modus 👇", chooseRound: "👇 Wähle Wahrheit oder Pflicht 👇", chooseRomantic: "👇 Romantischer Modus: Wahrheit oder Pflicht 👇", chooseSpicy: "👇 Pikanter Modus: Wahrheit oder Pflicht 👇", softBadge: "Sanfter Modus", romanticBadge: "Romantischer Modus", spicyBadge: "Pikanter Modus", truthBadge: "Wahrheit", dareBadge: "Pflicht" };
const questionText = document.getElementById('questionText');
const nextButton = document.getElementById('nextButton');
const resetButton = document.getElementById('resetButton');
const backButton = document.getElementById('backButton');
const selectedType = document.getElementById('selectedType');
const selectedDifficulty = document.getElementById('selectedDifficulty');
const difficultyButtons = document.getElementById('difficultyButtons');
const choiceButtons = document.getElementById('choiceButtons');
function selectDifficulty(difficulty) {
  gameData.currentDifficulty = difficulty;
  if (difficulty === 'soft') { selectedDifficulty.innerHTML = '<span class="badge bg-success">' + t.softBadge + '</span>'; questionText.textContent = t.chooseRound; }
  else if (difficulty === 'romantic') { selectedDifficulty.innerHTML = '<span class="badge bg-primary">' + t.romanticBadge + '</span>'; questionText.textContent = t.chooseRomantic; }
  else { selectedDifficulty.innerHTML = '<span class="badge bg-warning">' + t.spicyBadge + '</span>'; questionText.textContent = t.chooseSpicy; }
  selectedDifficulty.style.display='block'; difficultyButtons.style.display='none'; choiceButtons.style.display='flex'; backButton.style.display='inline-block';
}
function selectChoice(type) { gameData.currentType=type; const questions=gameData.questions[gameData.currentDifficulty][type]; questionText.textContent=questions[Math.floor(Math.random()*questions.length)]; selectedType.innerHTML = type==='truth' ? '<span class="badge bg-info">'+t.truthBadge+'</span>' : '<span class="badge bg-danger">'+t.dareBadge+'</span>'; selectedType.style.display='block'; nextButton.style.display='inline-block'; resetButton.style.display='inline-block'; choiceButtons.style.display='none'; }
function nextQuestion() { if(!gameData.currentType||!gameData.currentDifficulty)return; const questions=gameData.questions[gameData.currentDifficulty][gameData.currentType]; questionText.textContent=questions[Math.floor(Math.random()*questions.length)]; }
function backToDifficulty() { gameData.currentType=null; questionText.textContent=t.choose; selectedType.style.display='none'; nextButton.style.display='none'; resetButton.style.display='none'; backButton.style.display='none'; choiceButtons.style.display='none'; difficultyButtons.style.display='flex'; }
function resetGame() { gameData.currentType=null; gameData.currentDifficulty=null; questionText.textContent=t.choose; selectedType.style.display='none'; selectedDifficulty.style.display='none'; nextButton.style.display='none'; resetButton.style.display='none'; backButton.style.display='none'; choiceButtons.style.display='none'; difficultyButtons.style.display='flex'; }
