// Define Portuguese answers - run as early as possible, outside DOMContentLoaded
window.ptAnswers = {
    classic: [
        "É certo.",
        "Decididamente sim.",
        "Sem dúvida.",
        "Sim, definitivamente.",
        "Você pode confiar nisso.",
        "Como eu vejo, sim.",
        "Muito provável.",
        "As perspectivas são boas.",
        "Sim.",
        "Os sinais apontam para sim.",
        "Resposta nebulosa, tente novamente.",
        "Pergunte novamente mais tarde.",
        "Melhor não te dizer agora.",
        "Não posso prever agora.",
        "Concentre-se e pergunte novamente.",
        "Não conte com isso.",
        "Minha resposta é não.",
        "Minhas fontes dizem não.",
        "As perspectivas não são tão boas.",
        "Muito duvidoso."
    ],
    silly: [
        "Tão certo quanto unicórnios são reais!",
        "Minha bola de cristal diz SIM!",
        "Absolutamente... NÃO!",
        "As estrelas se alinham para dizer talvez?",
        "Me pergunte depois do meu intervalo para café.",
        "O hamster mágico diz sim!",
        "Só se você pular em um pé só.",
        "Minha bola mágica 8 está de férias.",
        "A resposta está escondida debaixo da sua cama.",
        "Sim, mas apenas às terças-feiras.",
        "De jeito nenhum, José!",
        "O universo diz para tentar novamente.",
        "Isso é um não definitivo de mim.",
        "Sim, com granulado por cima!",
        "Minhas fontes estão rindo muito para responder.",
        "A resposta está soprando no vento.",
        "Pergunte ao seu pet, ele sabe melhor.",
        "A mágica diz sim, mas a lógica diz não.",
        "Só se porcos começarem a voar amanhã.",
        "A resposta é 42. Sempre 42."
    ],
    sarcastic: [
        "Ah, absolutamente. E eu sou a Rainha da Inglaterra.",
        "Deixe-me verificar minha bola de cristal... diz 'obviamente não'.",
        "Claro, e unicórnios são reais também.",
        "A água não é molhada?",
        "Eu diria sim, mas estaria mentindo.",
        "Em que universo isso seria verdade?",
        "Uau, você realmente perguntou isso?",
        "Vou fingir que você não perguntou isso.",
        "Hmm, deixe-me pensar... não.",
        "As chances são um pouco piores do que ganhar na loteria. Duas vezes.",
        "Eu poderia responder, mas estou ocupado revirando os olhos.",
        "Você realmente precisa que eu responda isso?",
        "Estou rindo demais para responder adequadamente.",
        "Ah, querido, não.",
        "Claro, quando porcos voarem em primeira classe.",
        "Apostaria meu dinheiro inexistente em 'não'.",
        "Isso é hilário. Próxima pergunta, por favor.",
        "Você está falando sério agora?",
        "Vou precisar de mais café antes de responder isso.",
        "A resposta é tão óbvia que nem vou dizer."
    ],
    romance: [
        "O amor está no ar!",
        "Seu coração já sabe a resposta.",
        "A flecha do Cupido nunca erra.",
        "As estrelas se alinham para o romance.",
        "O amor encontrará um caminho.",
        "Nem todos que vagam no amor estão perdidos.",
        "Siga seu coração neste.",
        "O amor é paciente; talvez você devesse ser também.",
        "O coração quer o que quer.",
        "O romance está logo ali na esquina.",
        "Este amor foi escrito nas estrelas.",
        "Talvez seja hora de dar o primeiro passo.",
        "O amor é uma jornada, não um destino.",
        "Seu futuro romântico parece brilhante!",
        "Confie no processo do amor.",
        "Às vezes o amor precisa de um pouco de tempo.",
        "As melhores histórias de amor levam tempo para se desenvolver.",
        "Seu coração não te levará pelo caminho errado.",
        "O amor vem quando você menos espera.",
        "Esta conexão tem potencial."
    ],
    drinking: [
        "Beba, querido!",
        "Tome um shot!",
        "Fundo!",
        "Sua vez de beber!",
        "Beba duas vezes!",
        "Todo mundo bebe!",
        "Pule sua vez, sortudo você!",
        "Escolha alguém para beber!",
        "Sem bebida desta vez!",
        "Saúde! Tome um gole!",
        "Beba água, mantenha-se hidratado!",
        "A última pessoa a levantar a mão bebe!",
        "Conte uma piada ou beba!",
        "Beba se você já...",
        "Pedra, papel, tesoura com seu vizinho. Perdedor bebe!",
        "Beba se você está usando azul!",
        "Tome um gole para cada pet que você tem!",
        "Beba se você checou seu celular nos últimos 10 minutos!",
        "A pessoa mais alta bebe!",
        "Beba se você maratonou uma série esta semana!"
    ]
};
