const gameData = {
    currentType: null,
    currentDifficulty: null,
    questions: {
        soft: { truth: [
            "Si tu pouvais te transformer en animal, lequel choisirais-tu ?",
            "Quel était ton fantasme d'enfance le plus bizarre ?",
            "Quel est ton emoji préféré ?",
            "Si tu étais invisible pendant une journée, que ferais-tu ?",
            "Quelle est ta citation de film préférée ?",
            "Quel est la chose la plus ennuyeuse que tu aies jamais faite ?",
            "Quel est ton souvenir d'enfance préféré ?",
            "De quoi es-tu le plus fier ?",
            "Quelle est ta plus grande peur ?",
            "Quel est ton personnage de dessin animé préféré ?",
            "Quelle compétence aimerais-tu apprendre ?",
            "Quelle est ta saison préférée ?",
            "Quel est ton moment préféré de la journée ?",
            "Quel animal aimerais-tu avoir comme animal de compagnie ?",
            "Quel est ton temps préféré ?",
            "Quel parc d'attractions aimerais-tu visiter ?",
            "Quel est ton snack préféré ?",
            "Quel emploi aimerais-tu essayer pendant une journée ?",
            "Quelle est ton odeur préférée ?",
            "Quel type de maison aimerais-tu habiter ?",
            "Si tu pouvais avoir un superpouvir, lequel choisirais-tu ?",
            "Si tu pouvais voyager dans le temps, qu'aimerais-tu changer ?",
            "Si tu pouvais être une célébrité pendant une journée, qui choisirais-tu ?",
            "Quel est ton personnage fictif préféré ?",
            "Si tu pouvais inventer un nouveau plat, ce serait quoi ?",
            "Quel est ta fête préférée et pourquoi ?",
            "Si tu pouvais vivre dans le monde d'un film ou d'une série, lequel choisirais-tu ?",
            "Quel est ta destination de rêve ?",
            "Si tu pouvais changer une chose au monde, ce serait quoi ?",
            "Quel est ton jeu d'enfance préféré ?",
            "Si tu pouvais créer une nouvelle fête, ce serait comment ?",
            "Si tu pouvais discuter avec une figure historique, qui choisirais-tu ?",
            "Si tu pouvais posséder un objet magique, ce serait quoi ?",
            "Si tu pouvais être le personnage principal d'un livre, lequel choisirais-tu ?",
            "Si tu pouvais construire ta maison de rêve, à quoi ressemblerait-elle ?",
            "Si tu pouvais faire un film, quel genre choisirais-tu ?",
            "Si tu pouvais ouvrir n'importe quel type de magasin, ce serait quoi ?",
            "Si tu pouvais concevoir un jeu, quel type serait-ce ?",
            "Si tu pouvais avoir un assistant robot, que voudrais-tu qu'il fasse ?",
            "Si tu pouvais créer un nouveau sport, ce serait quoi ?",
            "Préfères-tu la baguette, le pain de mie ou la brioche ?",
            "Aimes-tu plus le vin blanc, le vin rouge ou le vin rosé ?",
            "Quelle est ta couleur préférée ?",
            "Préfères-tu la musique française, le jazz ou la musique classique ?",
            "Quel est ton sport français préféré : équitation, cyclisme, foot ou rugby ?",
            "Quel auteur français aimes-tu le plus lire ?",
            "Quel film français est ton préféré ?",
            "Quelle série télévisée française regardes-tu ?",
            "Préfères-tu les jeux de société ou les jeux de cartes ?",
            "Utilises-tu plutôt Instagram, TikTok ou Facebook ?"
], dare: [
            "Marche comme un pingouin",
            "Parle avec une voix bizarre jusqu'au prochain tour",
            "Imite une célébrité jusqu'au prochain tour",
            "Porte des chaussettes comme gants pendant 5 minutes",
            "Essaie de te lécher le nez (ou le coude)",
            "Dis 'Je suis si beau/belle' au miroir 10 fois",
            "Parle avec un faux accent étranger pendant 5 minutes",
            "Agis comme un chat - mouvements et bruits",
            "Agis comme un chien - mouvements et bruits",
            "Prétends être un robot quand tu parles",
            "Écris des lettres avec tes fesses",
            "Dessine un autoportrait les yeux fermés",
            "Écris ton nom avec tes orteils en tenant un stylo",
            "Imite un bébé qui pleure pendant 30 secondes",
            "Prétends nager",
            "Marche comme une personne âgée",
            "Saute comme une grenouille 10 fois",
            "Prends une pose de superhéros",
            "Prétends conduire une voiture",
            "Imite le bruit d'un éternuement",
            "Fais 10 pompes en style français (avec élégance)",
            "Effectue l'arabesque (posture de ballet français)",
            "Danse un tango ou une valse",
            "Chante 'La Vie en Rose' ou une chanson de Jacques Brel",
            "Récite un passage de Molière ou Victor Hugo",
            "Raconte une blague française typique",
            "Effectue une courte scène de Théâtre du Vieux Belleville",
            "Dessine un portrait dans le style cubiste français",
            "Fais 5 abdominaux tout en parlant français avec accent",
            "Décris la Joconde sans mentionner son sourire",
            "Chante 'La Marseillaise' avec passion",
            "Imite un serveur français snobbiste de restaurant",
            "Effectue un mime français à la Charlie Chaplin",
            "Fais une pose de yoga comme dans un hatha yoga français",
            "Applaudis à la française (lentement et avec élégance)",
            "Marche comme un Parisien chic pendant 10 pas",
            "Marche en équilibrant une baguette sur ta tête",
            "Tourne sur place 10 fois en levant un verre invisible",
            "Saute à la corde (prétends) 50 fois en disant 'Oh là là !'",
            "Fais une grimace typiquement française (moue)",
            "Fais deux bises à quelqu'un (à la française)",
            "Offre un verre à quelqu'un (en prétendant)",
            "Fais une surprise avec un toast à quelqu'un",
            "Complimente sincèrement le style de quelqu'un",
            "Lève un verre à tout le monde présent",
            "Fais un massage des épaules à quelqu'un de manière relaxante",
            "Fait une blague avec quelqu'un 10 fois",
            "Partage une blague typiquement française avec quelqu'un",
            "Danse un valse avec quelqu'un",
            "Laisse quelqu'un te coiffer à la française"
] },
        romantic: { truth: [
            "Si tu pouvais te transformer en animal, lequel choisirais-tu ?",
            "Quel était ton fantasme d'enfance le plus bizarre ?",
            "Quel est ton emoji préféré ?",
            "Si tu étais invisible pendant une journée, que ferais-tu ?",
            "Quelle est ta citation de film préférée ?",
            "Quel est la chose la plus ennuyeuse que tu aies jamais faite ?",
            "Quel est ton souvenir d'enfance préféré ?",
            "De quoi es-tu le plus fier ?",
            "Quelle est ta plus grande peur ?",
            "Quel est ton personnage de dessin animé préféré ?",
            "Quelle compétence aimerais-tu apprendre ?",
            "Quelle est ta saison préférée ?",
            "Quel est ton moment préféré de la journée ?",
            "Quel animal aimerais-tu avoir comme animal de compagnie ?",
            "Quel est ton temps préféré ?",
            "Quel parc d'attractions aimerais-tu visiter ?",
            "Quel est ton snack préféré ?",
            "Quel emploi aimerais-tu essayer pendant une journée ?",
            "Quelle est ton odeur préférée ?",
            "Quel type de maison aimerais-tu habiter ?",
            "Si tu pouvais avoir un superpouvir, lequel choisirais-tu ?",
            "Si tu pouvais voyager dans le temps, qu'aimerais-tu changer ?",
            "Si tu pouvais être une célébrité pendant une journée, qui choisirais-tu ?",
            "Quel est ton personnage fictif préféré ?",
            "Si tu pouvais inventer un nouveau plat, ce serait quoi ?",
            "Quel est ta fête préférée et pourquoi ?",
            "Si tu pouvais vivre dans le monde d'un film ou d'une série, lequel choisirais-tu ?",
            "Quel est ta destination de rêve ?",
            "Si tu pouvais changer une chose au monde, ce serait quoi ?",
            "Quel est ton jeu d'enfance préféré ?",
            "Si tu pouvais créer une nouvelle fête, ce serait comment ?",
            "Si tu pouvais discuter avec une figure historique, qui choisirais-tu ?",
            "Si tu pouvais posséder un objet magique, ce serait quoi ?",
            "Si tu pouvais être le personnage principal d'un livre, lequel choisirais-tu ?",
            "Si tu pouvais construire ta maison de rêve, à quoi ressemblerait-elle ?",
            "Si tu pouvais faire un film, quel genre choisirais-tu ?",
            "Si tu pouvais ouvrir n'importe quel type de magasin, ce serait quoi ?",
            "Si tu pouvais concevoir un jeu, quel type serait-ce ?",
            "Si tu pouvais avoir un assistant robot, que voudrais-tu qu'il fasse ?",
            "Si tu pouvais créer un nouveau sport, ce serait quoi ?",
            "Préfères-tu la baguette, le pain de mie ou la brioche ?",
            "Aimes-tu plus le vin blanc, le vin rouge ou le vin rosé ?",
            "Quelle est ta couleur préférée ?",
            "Préfères-tu la musique française, le jazz ou la musique classique ?",
            "Quel est ton sport français préféré : équitation, cyclisme, foot ou rugby ?",
            "Quel auteur français aimes-tu le plus lire ?",
            "Quel film français est ton préféré ?",
            "Quelle série télévisée française regardes-tu ?",
            "Préfères-tu les jeux de société ou les jeux de cartes ?",
            "Utilises-tu plutôt Instagram, TikTok ou Facebook ?"
], dare: [
            "Marche comme un pingouin",
            "Parle avec une voix bizarre jusqu'au prochain tour",
            "Imite une célébrité jusqu'au prochain tour",
            "Porte des chaussettes comme gants pendant 5 minutes",
            "Essaie de te lécher le nez (ou le coude)",
            "Dis 'Je suis si beau/belle' au miroir 10 fois",
            "Parle avec un faux accent étranger pendant 5 minutes",
            "Agis comme un chat - mouvements et bruits",
            "Agis comme un chien - mouvements et bruits",
            "Prétends être un robot quand tu parles",
            "Écris des lettres avec tes fesses",
            "Dessine un autoportrait les yeux fermés",
            "Écris ton nom avec tes orteils en tenant un stylo",
            "Imite un bébé qui pleure pendant 30 secondes",
            "Prétends nager",
            "Marche comme une personne âgée",
            "Saute comme une grenouille 10 fois",
            "Prends une pose de superhéros",
            "Prétends conduire une voiture",
            "Imite le bruit d'un éternuement",
            "Fais 10 pompes en style français (avec élégance)",
            "Effectue l'arabesque (posture de ballet français)",
            "Danse un tango ou une valse",
            "Chante 'La Vie en Rose' ou une chanson de Jacques Brel",
            "Récite un passage de Molière ou Victor Hugo",
            "Raconte une blague française typique",
            "Effectue une courte scène de Théâtre du Vieux Belleville",
            "Dessine un portrait dans le style cubiste français",
            "Fais 5 abdominaux tout en parlant français avec accent",
            "Décris la Joconde sans mentionner son sourire",
            "Chante 'La Marseillaise' avec passion",
            "Imite un serveur français snobbiste de restaurant",
            "Effectue un mime français à la Charlie Chaplin",
            "Fais une pose de yoga comme dans un hatha yoga français",
            "Applaudis à la française (lentement et avec élégance)",
            "Marche comme un Parisien chic pendant 10 pas",
            "Marche en équilibrant une baguette sur ta tête",
            "Tourne sur place 10 fois en levant un verre invisible",
            "Saute à la corde (prétends) 50 fois en disant 'Oh là là !'",
            "Fais une grimace typiquement française (moue)",
            "Fais deux bises à quelqu'un (à la française)",
            "Offre un verre à quelqu'un (en prétendant)",
            "Fais une surprise avec un toast à quelqu'un",
            "Complimente sincèrement le style de quelqu'un",
            "Lève un verre à tout le monde présent",
            "Fais un massage des épaules à quelqu'un de manière relaxante",
            "Fait une blague avec quelqu'un 10 fois",
            "Partage une blague typiquement française avec quelqu'un",
            "Danse un valse avec quelqu'un",
            "Laisse quelqu'un te coiffer à la française"
] },
        spicy: { truth: [
            "Quand as-tu menti pour la dernière fois ? À qui ?",
            "As-tu secrètement aimé quelqu'un ici ?",
            "Quel est ton moment le plus embarrassant ?",
            "Qu'est-ce qui t'a fait pleurer le plus fort ?",
            "Qui as-tu eu un crush ? Tu lui parles encore ?",
            "Quelle est ta plus mémorable expérience romantique ?",
            "À quoi ressemble ta date idéale ?",
            "Qu'est-ce que tu as fait de plus fou pour l'amour ?",
            "Quelle est la chose que tu aimes le moins chez toi ?",
            "Quand as-tu senti le plus de culpabilité ?",
            "Quelle habitude as-tu que les autres ne connaissent pas ?",
            "Quel est ton plus grand regret ?",
            "Quelle est la chose la plus impulsive que tu aies faite ?",
            "Qu'aimerais-tu le plus dire à quelqu'un ?",
            "Quel est quelque chose que tu ne veux pas que les autres sachent ?",
            "Quelle est la chose la plus infantile que tu aies faite ?",
            "Quel souvenir voudrais-tu oublier ?",
            "Quelle est ta plus grande préoccupation pour l'avenir ?",
            "Qu'as-tu fait secrètement que tu ne veux pas découvrir ?",
            "Quelle est la chose la plus embarrassante que tu aies faite ?",
            "Comment était ton premier baiser ? Était-ce romantique ou maladroit ?",
            "As-tu déjà eu une situation sentimentale compliquée avec deux personnes ?",
            "Envisagerais-tu une relation ouverte à la française ?",
            "Quelle était la rupture la plus difficile de ta vie ?",
            "As-tu déjà rompu une relation de manière blessante ?",
            "Combien de relations sérieuses as-tu eu jusqu'à présent ?",
            "Y a-t-il quelqu'un dans le groupe qui t'attire ?",
            "Quel mensonge as-tu dit dans une relation pour éviter un conflit ?",
            "As-tu déjà eu une amitié qui semblait être plus qu'une amitié ?",
            "Choisirait-tu un partenaire riche mais ennuyeux ou pauvre mais passionné ?",
            "As-tu déjà regardé le téléphone de ton partenaire sans permission ?",
            "As-tu déjà maintenu une relation à distance ?",
            "Qu'en est-il de fréquenter l'ex-partenaire d'un ami proche ?",
            "Y a-t-il un ex avec lequel tu aimerais réessayer ?",
            "Quel scénario romantique as-tu rêvé secrètement ?",
            "T'es-tu déjà senti attiré par quelqu'un du même sexe ?",
            "Quel acteur/actrice français admires-tu le plus ?",
            "Accepterais-tu une relation où vous êtes libres de voir d'autres personnes ?",
            "T'es-tu déjà senti attiré par un professeur ou quelqu'un d'une position supérieure ?",
            "Quel est ton fantasme romantique secret ?",
            "Qu'est-ce dont tu as été en colère contre un ami ?",
            "Qu'est-ce dont tu as été en colère contre ta famille ?",
            "Quel trait détestes-tu le plus chez quelqu'un ici ?",
            "Qu'as-tu dit derrière le dos de quelqu'un ici ?",
            "Qu'envies-tu chez quelqu'un ici ?",
            "Qui ici penses-tu qui est le plus faux ?",
            "Qui ici penses-tu qui est le plus narcissique ?",
            "Qui voudrais-tu le plus gifler ?",
            "Qui penses-tu qui mérite le moins sa vie actuelle ?",
            "Quel type de personne méprises-tu le plus ?"
], dare: [
            "Écris ton nom avec tes fesses",
            "Dessine un motif sur ton visage avec du rouge à lèvres",
            "Fais semblant d'être saoul",
            "Fais semblant d'être en colère",
            "Lèche ton nez avec ta langue",
            "Enlève tes chaussettes et laisse d'autres les sentir",
            "Fais semblant d'avoir des contractions de travail",
            "Porte des vêtements du sexe opposé et prends une photo",
            "Laisse d'autres écrire sur ton corps",
            "Laisse d'autres te nourrir les yeux fermés",
            "Laisse d'autres te maquiller",
            "Fais semblant de ton expérience la plus embarrassante",
            "Imite la personne que tu détestes le plus",
            "Prends un selfie exagéré",
            "Fais semblant d'avoir peur de la plupart",
            "Imite un bébé qui pleure",
            "Assieds-toi sur un ballon jusqu'à ce qu'il éclate avec tes fesses",
            "Fais semblant de la nervosité de ta première date",
            "Imite comment tu as l'air quand tu es saoul",
            "Fais semblant de ta réaction quand tu es effrayé",
            "Envoie un message à ton ex 'Je me demande comment tu vas'",
            "Chante 'La Vie en Rose' fort en public",
            "Fais la bise à un étranger dans la rue",
            "Publie une photo non-retouchée de toi sur les réseaux sociaux",
            "Appelle un restaurant en prétendant être un critique gastronomique",
            "Danse une valse seul(e) en public",
            "Publie 'J'aime quelqu'un' sur les réseaux sociaux",
            "Appelle quelqu'un en faisant semblant d'être inspecteur de la Sûreté",
            "Déclame 'À bas les hypocrites !' en public (comme Victor Hugo)",
            "Appelle quelqu'un en parlant avec un accent français exagéré",
            "Dis à un étranger dans la rue ce que tu penses vraiment",
            "Avoue publiquement ton moment le plus maladroit",
            "Dis à haute voix quel acteur français tu trouves le plus attirant",
            "Appelle quelqu'un que tu as offensé et excuse-toi sincèrement",
            "Partage un secret modéré que tu gardais caché",
            "Montre aux autres ta photo la plus embarrassante",
            "Imite publiquement quelqu'un que tu juges sévèrement",
            "Dis à haute voix une insécurité que tu as",
            "Exprime ton opinion honnête sur le style de quelqu'un",
            "Donne une apologie sincère pour un acte passé",
            "Partage ton plus grand regret ou réalisation",
            "Fais un baiser sur la joue à quelqu'un",
            "Fais un massage des épaules à quelqu'un",
            "Fais un câlin à quelqu'un pendant 30 secondes",
            "Assieds-toi sur les genoux de quelqu'un",
            "Laisse quelqu'un te coiffer",
            "Tiens la main avec quelqu'un et tourne autour",
            "Fais un long câlin à quelqu'un",
            "Prends une photo joue contre joue avec quelqu'un",
            "Laisse quelqu'un te dessiner sur le bras"
] }
    }
};
const t = { choose: "👇 Choisissez votre mode couple 👇", chooseRound: "👇 Choisissez Vérité ou Action 👇", chooseRomantic: "👇 Mode romantique: Vérité ou Action 👇", chooseSpicy: "👇 Mode épicé: Vérité ou Action 👇", softBadge: "Mode doux", romanticBadge: "Mode romantique", spicyBadge: "Mode épicé", truthBadge: "Vérité", dareBadge: "Action" };
const questionText = document.getElementById('questionText');
const nextButton = document.getElementById('nextButton');
const resetButton = document.getElementById('resetButton');
const backButton = document.getElementById('backButton');
const selectedType = document.getElementById('selectedType');
const selectedDifficulty = document.getElementById('selectedDifficulty');
const difficultyButtons = document.getElementById('difficultyButtons');
const choiceButtons = document.getElementById('choiceButtons');
function selectDifficulty(difficulty) {
  gameData.currentDifficulty = difficulty;
  if (difficulty === 'soft') { selectedDifficulty.innerHTML = '<span class="badge bg-success">' + t.softBadge + '</span>'; questionText.textContent = t.chooseRound; }
  else if (difficulty === 'romantic') { selectedDifficulty.innerHTML = '<span class="badge bg-primary">' + t.romanticBadge + '</span>'; questionText.textContent = t.chooseRomantic; }
  else { selectedDifficulty.innerHTML = '<span class="badge bg-warning">' + t.spicyBadge + '</span>'; questionText.textContent = t.chooseSpicy; }
  selectedDifficulty.style.display='block'; difficultyButtons.style.display='none'; choiceButtons.style.display='flex'; backButton.style.display='inline-block';
}
function selectChoice(type) { gameData.currentType=type; const questions=gameData.questions[gameData.currentDifficulty][type]; questionText.textContent=questions[Math.floor(Math.random()*questions.length)]; selectedType.innerHTML = type==='truth' ? '<span class="badge bg-info">'+t.truthBadge+'</span>' : '<span class="badge bg-danger">'+t.dareBadge+'</span>'; selectedType.style.display='block'; nextButton.style.display='inline-block'; resetButton.style.display='inline-block'; choiceButtons.style.display='none'; }
function nextQuestion() { if(!gameData.currentType||!gameData.currentDifficulty)return; const questions=gameData.questions[gameData.currentDifficulty][gameData.currentType]; questionText.textContent=questions[Math.floor(Math.random()*questions.length)]; }
function backToDifficulty() { gameData.currentType=null; questionText.textContent=t.choose; selectedType.style.display='none'; nextButton.style.display='none'; resetButton.style.display='none'; backButton.style.display='none'; choiceButtons.style.display='none'; difficultyButtons.style.display='flex'; }
function resetGame() { gameData.currentType=null; gameData.currentDifficulty=null; questionText.textContent=t.choose; selectedType.style.display='none'; selectedDifficulty.style.display='none'; nextButton.style.display='none'; resetButton.style.display='none'; backButton.style.display='none'; choiceButtons.style.display='none'; difficultyButtons.style.display='flex'; }
